const cards=[['안녕하세요','您好 / 你好','안녕（安宁）+ 하세요（请这样做）→ 祝你安宁','선생님, 안녕하세요?','问候'],['감사합니다','谢谢','감사（感谢）+ 합니다（正式陈述）','도와주셔서 감사합니다.','问候'],['학생','学生','汉字词：学生，和学校、学习成组记','저는 학생이에요.','身份'],['선생님','老师','선생（先生）+ 님（尊称）','선생님은 한국 사람이에요.','身份'],['친구','朋友','汉字词“亲旧”：亲近的老相识','이 사람은 제 친구예요.','人物'],['학교','学校','汉字词：学校；학 常和学习相关','학교에 갑니다.','地点'],['책','书','和 책상（书桌）结对记','이것은 한국어 책이에요.','物品'],['한국어','韩语','한국（韩国）+ 어（语言）','한국어를 공부합니다.','学习'],['이름','名字','和 이름이 뭐예요? 整句一起记','이름이 뭐예요?','介绍'],['나라','国家','和 어느 나라（哪个国家）成组记','어느 나라 사람이에요?','介绍'],['사람','人','中国人=중국 사람；韩国人=한국 사람','저는 중국 사람이에요.','身份'],['회사원','公司职员','회사（公司）+ 원（人员）','제 친구는 회사원이에요.','职业'],['의사','医生','汉字词：医师；无收音，后接 예요','민수 씨는 의사예요.','职业'],['네','是 / 好的','应答词；和 아니요 成对记','네, 맞아요.','应答'],['아니요','不 / 不是','与 네 成对记','아니요, 학생이 아니에요.','应答'],['어느','哪个','必须放在名词前：어느 나라','어느 학교에 다녀요?','疑问'],['뭐','什么','무엇 的口语缩略','이것은 뭐예요?','疑问'],['저','我（谦称）','正式场合用 저；熟人间用 나','저는 코코예요.','人物'],['제','我的（谦称）','저의 的缩略','제 이름은 코코예요.','人物'],['맞아요','对 / 没错','맞다 + 아요','네, 맞아요.','应答'],['공부하다','学习','공부 + 하다','매일 한국어를 공부해요.','动作'],['읽다','读','常读作 [익따]，先记声音','책을 읽어요.','动作'],['듣다','听','和 읽다 成对记','한국 노래를 들어요.','动作'],['말하다','说','말 + 하다 → 说话','한국어로 말해요.','动作']];
const phrases=[['안녕하세요. 저는 코코예요.','你好，我是 Coco。','初次见面'],['저는 중국 사람이에요.','我是中国人。','自我介绍'],['한국어를 공부해요.','我学习韩语。','学习日常'],['이것은 제 책이에요.','这是我的书。','物品介绍'],['친구가 있어요.','我有朋友。','人物关系'],['선생님, 감사합니다.','老师，谢谢您。','课堂表达']];
const patterns=[['N은/는 N이에요/예요','N 是 N','有收音用 이에요；无收音用 예요。은/는 标记话题。','저는 중국 사람이에요.'],['N이/가 있어요','有 N / N 在','有收音用 이；无收音用 가。있어요 表示存在。','책이 있어요.'],['N을/를 V','动作对象是 N','有收音用 을；无收音用 를。把它想成动作箭头。','한국어를 공부해요.'],['N이/가 아니에요','不是 N','把 아니에요 作为一个整体记。','저는 의사가 아니에요.'],['N도','N 也……','도 直接替换主题、主语或宾语助词。','저도 학생이에요.'],['N의 N','N 的 N','의 表示所属；저의 常缩成 제。','이것은 제 책이에요.']];
const qs=[['review','唤醒记忆','复习到期词'],['input','听力输入','听写 3 句'],['pattern','句型替换','替换 5 组'],['output','口语输出','跟读 5 句'],['mistake','错误归档','记录错因']];
let idx=0,flip=false,listenIdx=0,speakIdx=0,scores=JSON.parse(localStorage.getItem('hanstep-progress')||'{}'),xp=Number(localStorage.getItem('hanstep-xp')||0),done=JSON.parse(localStorage.getItem('hanstep-quests')||'{}');
function save(){localStorage.setItem('hanstep-progress',JSON.stringify(scores));localStorage.setItem('hanstep-xp',String(xp));localStorage.setItem('hanstep-quests',JSON.stringify(done));render()}
function speakKorean(text,rate=0.9){if(!('speechSynthesis'in window))return alert('当前浏览器不支持语音播放');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=rate;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase().startsWith('ko'))||null;speechSynthesis.speak(u)}
function render(){const c=cards[idx],m=Object.entries(scores).filter(([k,v])=>!k.startsWith('_')&&v>=3).length,p=Math.round(m/cards.length*100);document.querySelector('#tag').textContent=flip?'拆开记':c[4];document.querySelector('#ko').textContent=flip?c[1]:c[0];document.querySelector('#hint').textContent=flip?`${c[2]} · ${c[3]}`:'点击查看记忆线索';document.querySelector('#count').textContent=`${idx+1} / ${cards.length}`;document.querySelector('#mastered').textContent=m;document.querySelector('#progressText').textContent=`24 个起步词 · ${p}%`;document.querySelector('#ring').style.setProperty('--progress',p*3.6+'deg');document.querySelector('#status').textContent=`Lv.${Math.floor(xp/200)+1} · ${xp} XP`;document.querySelector('#listenCount').textContent=scores._listen||0;document.querySelector('#speakCount').textContent=scores._speak||0;document.querySelector('#quests').innerHTML=qs.map(q=>`<button data-q="${q[0]}" class="${done[q[0]]?'done':''}"><span class="check">${done[q[0]]?'✓':''}</span><div><h3>${q[1]}</h3><small>${q[2]} · +20 XP</small></div></button>`).join('');document.querySelector('#stars').textContent=`${Object.values(done).filter(Boolean).length} / 5 完成`;document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const k=b.dataset.q;if(!done[k])xp+=20;done[k]=!done[k];save()});renderListen();renderSpeak()}
function renderListen(){const p=phrases[listenIdx];document.querySelector('#listenNo').textContent=String(listenIdx+1).padStart(2,'0');document.querySelector('#listenKorean').textContent=p[0];document.querySelector('#listenMeaning').textContent=p[1];document.querySelector('#listenAnswer').hidden=true;document.querySelector('#dictationInput').value='';document.querySelector('#dictationFeedback').textContent=''}
function renderSpeak(){const p=phrases[speakIdx];document.querySelector('#speakScene').textContent=p[2];document.querySelector('#speakKorean').textContent=p[0];document.querySelector('#speakMeaning').textContent=p[1]}
function normalizeKorean(s){return s.replace(/[\s.,!?，。！？]/g,'').toLowerCase()}
document.querySelectorAll('[data-view-link],[data-go]').forEach(b=>b.onclick=e=>{e.preventDefault();const id=b.dataset.viewLink||b.dataset.go;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view-link]').forEach(n=>n.classList.toggle('active',n.dataset.viewLink===id));document.querySelector('#sidebar').classList.remove('open');location.hash=id;window.scrollTo(0,0)});
document.querySelector('#menuButton').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#card').onclick=()=>{flip=!flip;render()};document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.rate);scores[cards[idx][0]]=v;xp+=(v+1)*3;idx=(idx+1)%cards.length;flip=false;save()});document.querySelector('#reset').onclick=()=>{if(confirm('确定重置所有学习进度吗？')){scores={};xp=0;done={};save()}};
document.querySelector('#playNormal').onclick=()=>speakKorean(phrases[listenIdx][0],.9);document.querySelector('#playSlow').onclick=()=>speakKorean(phrases[listenIdx][0],.68);document.querySelector('#revealListen').onclick=()=>document.querySelector('#listenAnswer').hidden=false;document.querySelector('#checkDictation').onclick=()=>{const input=normalizeKorean(document.querySelector('#dictationInput').value),answer=normalizeKorean(phrases[listenIdx][0]),ok=input===answer;document.querySelector('#dictationFeedback').textContent=ok?'✓ 完全正确！再跟读一遍，把声音也记住。':`还差一点。正确答案：${phrases[listenIdx][0]}`;document.querySelector('#listenAnswer').hidden=false;scores._listen=(scores._listen||0)+1;xp+=ok?12:5;save()};document.querySelector('#nextListen').onclick=()=>{listenIdx=(listenIdx+1)%phrases.length;renderListen()};
document.querySelector('#modelVoice').onclick=()=>speakKorean(phrases[speakIdx][0],.86);document.querySelector('#nextSpeak').onclick=()=>{speakIdx=(speakIdx+1)%phrases.length;renderSpeak()};document.querySelectorAll('[data-speech-rate]').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.speechRate);scores._speak=(scores._speak||0)+1;xp+=v*5;document.querySelector('#speechFeedback').textContent=v===3?'太好了。现在尝试不看文字再说一次。':'已记录。再听一次，重点模仿整句的节奏。';save()});
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelector('#recordVoice').onclick=()=>{if(!Recognition){document.querySelector('#speechFeedback').textContent='当前浏览器暂不支持语音识别。你仍可用系统录音机录下自己，与示范音对比。';return}const r=new Recognition();r.lang='ko-KR';r.interimResults=false;const btn=document.querySelector('#recordVoice'),wave=document.querySelector('#wave');btn.classList.add('active');btn.textContent='● 正在听你说…';wave.classList.add('active');r.onresult=e=>{const heard=e.results[0][0].transcript,goal=normalizeKorean(phrases[speakIdx][0]),match=normalizeKorean(heard)===goal;document.querySelector('#speechFeedback').textContent=`识别到：${heard}。${match?'整句识别成功！':'可以再慢一点，注意句尾。'}`;scores._speak=(scores._speak||0)+1;xp+=match?15:7;save()};r.onerror=()=>document.querySelector('#speechFeedback').textContent='没有听清。请允许麦克风权限，并靠近一点再试。';r.onend=()=>{btn.classList.remove('active');btn.textContent='● 开始跟读';wave.classList.remove('active')};r.start()};
document.querySelector('#patternGrid').innerHTML=patterns.map((p,i)=>`<article><span>0${i+1}</span><h2>${p[0]}</h2><b>${p[1]}</b><p>${p[2]}</p><blockquote>${p[3]}</blockquote></article>`).join('');const initial=location.hash.slice(1);if(initial&&document.querySelector(`#${initial}`))document.querySelector(`[data-view-link="${initial}"]`)?.click();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
