const cards=[['안녕하세요','您好 / 你好','안녕（安宁）+ 하세요（请这样做）→ 祝你安宁','선생님, 안녕하세요?','问候'],['감사합니다','谢谢','감사（感谢）+ 합니다（正式陈述）','도와주셔서 감사합니다.','问候'],['학생','学生','汉字词：学生，和学校、学习成组记','저는 학생이에요.','身份'],['선생님','老师','선생（先生）+ 님（尊称）','선생님은 한국 사람이에요.','身份'],['친구','朋友','汉字词“亲旧”：亲近的老相识','이 사람은 제 친구예요.','人物'],['학교','学校','汉字词：学校；학 常和学习相关','학교에 갑니다.','地点'],['책','书','和 책상（书桌）结对记','이것은 한국어 책이에요.','物品'],['한국어','韩语','한국（韩国）+ 어（语言）','한국어를 공부합니다.','学习'],['이름','名字','和 이름이 뭐예요? 整句一起记','이름이 뭐예요?','介绍'],['나라','国家','和 어느 나라（哪个国家）成组记','어느 나라 사람이에요?','介绍'],['사람','人','中国人=중국 사람；韩国人=한국 사람','저는 중국 사람이에요.','身份'],['회사원','公司职员','회사（公司）+ 원（人员）','제 친구는 회사원이에요.','职业'],['의사','医生','汉字词：医师；无收音，后接 예요','민수 씨는 의사예요.','职业'],['네','是 / 好的','应答词；和 아니요 成对记','네, 맞아요.','应答'],['아니요','不 / 不是','与 네 成对记','아니요, 학생이 아니에요.','应答'],['어느','哪个','必须放在名词前：어느 나라','어느 학교에 다녀요?','疑问'],['뭐','什么','무엇 的口语缩略','이것은 뭐예요?','疑问'],['저','我（谦称）','正式场合用 저；熟人间用 나','저는 코코예요.','人物'],['제','我的（谦称）','저의 的缩略','제 이름은 코코예요.','人物'],['맞아요','对 / 没错','맞다 + 아요','네, 맞아요.','应答'],['공부하다','学习','공부 + 하다','매일 한국어를 공부해요.','动作'],['읽다','读','常读作 [익따]，先记声音','책을 읽어요.','动作'],['듣다','听','和 읽다 成对记','한국 노래를 들어요.','动作'],['말하다','说','말 + 하다 → 说话','한국어로 말해요.','动作']];
const sounds=[['안녕하세요','按音节读 안-녕-하-세-요；句中自然连读即可。'],['감사함니다','받침 ㅂ 遇到鼻音 ㄴ，发生鼻音化：ㅂ → ㅁ，所以 합니다 听起来像 [함니다]。'],['학쌩','받침 ㄱ 后的松音 ㅅ 紧音化为 ㅆ：학생 → [학쌩]。'],['선생님','按音节 선-생-님；三个收音都要短促，不额外加元音。'],['친구','按音节 친-구；ㄴ 收音舌尖抵上齿龈。'],['학꾜','받침 ㄱ 后的 ㄱ 紧音化为 ㄲ：학교 → [학꾜]。'],['책','末尾 ㄱ 类收音只收住气流，不读成“克”。'],['한구거','前一音节收音 ㄱ 与后一音节元音相连：한국어 → [한구거]。'],['이름','ㅡ 不是“乌”，嘴唇放松、舌位靠后。'],['나라','两个音节清楚连接：나-라，ㄹ 是轻弹音。'],['사람','ㄹ 是轻弹音；ㅁ 收音闭唇结束。'],['회사원','회사원 常自然连读；ㅚ 在现代口语中接近 [웨]。'],['의사','词首 의 可规范读 [의]，口语中也常听见接近 [으]。'],['네','标准读 [네]，日常口语常听起来接近 [데]，不是拼错。'],['아니요','自然分为 아-니-요，不要把 니요 分得过开。'],['어느','ㅡ 嘴唇放松；读 어-느。'],['뭐','由 무엇이 缩略而来，读作一个音节 [뭐]。'],['저','ㅓ 类似“奥”和“额”之间，嘴巴自然张开。'],['제','ㅔ 与 ㅐ 在现代口语中常接近，读一个音节。'],['마자요','받침 ㅈ 遇元音时连到后面：맞아요 → [마자요]。'],['공부하다','按 공-부-하-다；ㅇ 收音是鼻音。'],['익따','읽다 的 겹받침 ㄺ 在这里读 ㄱ，且 ㄷ 紧音化：[익따]。'],['듣따','듣다 的 받침 ㄷ 后接 ㄷ，后一个 ㄷ 紧音化：[듣따]。'],['말하다','ㄹ 收音后接 ㅎ，保持轻快连接：말-하-다。']];
const phrases=[['안녕하세요. 저는 코코예요.','你好，我是 Coco。','初次见面'],['저는 중국 사람이에요.','我是中国人。','自我介绍'],['한국어를 공부해요.','我学习韩语。','学习日常'],['이것은 제 책이에요.','这是我的书。','物品介绍'],['친구가 있어요.','我有朋友。','人物关系'],['선생님, 감사합니다.','老师，谢谢您。','课堂表达']];
const patterns=[['N은/는 N이에요/예요','N 是 N','有收音用 이에요；无收音用 예요。은/는 标记话题。','저는 중국 사람이에요.','接续：名词+은/는；前词有收音用 은，无收音用 는。이에요/예요 也按收音选择。\n语感：先提出“说到 N”，再说明它是什么。\n易错：학생예요 × → 학생이에요 ✓','저는 학생이에요.\n민수는 의사예요.'],['N이/가 있어요','有 N / N 在','有收音用 이；无收音用 가。있어요 表示存在。','책이 있어요.','接续：名词有收音+이；无收音+가。\n用途① 拥有：친구가 있어요（有朋友）。\n用途② 存在：교실에 선생님이 있어요（老师在教室）。\n反义：없어요（没有/不在）。','시간이 있어요.\n학교에 친구가 있어요.'],['N을/를 V','动作对象是 N','有收音用 을；无收音用 를。把它想成动作箭头。','한국어를 공부해요.','接续：名词有收音+을；无收音+를。\n作用：标记动作直接作用的对象。\n记法：动作像箭头，箭头指向的名词后用 을/를。\n口语中上下文明确时偶尔省略，但初学阶段建议保留。','책을 읽어요.\n커피를 마셔요.'],['N이/가 아니에요','不是 N','把 아니에요 作为一个整体记。','저는 의사가 아니에요.','接续：名词+이/가 아니에요。\n有收音用 이，无收音用 가。\n아니에요 是固定形式，不写成 아니예요。\n与 이에요/예요 构成肯定和否定的一组。','학생이에요. ↔ 학생이 아니에요.\n의사가 아니에요.'],['N도','N 也……','도 直接替换主题、主语或宾语助词。','저도 학생이에요.','接续：名词后直接加 도。\n도 会替换 은/는、이/가、을/를，而不是叠加。\n저는→저도；커피를→커피도。\n表示和前文情况相同或追加一项。','민수도 학생이에요.\n커피도 마셔요.'],['N의 N','N 的 N','의 表示所属；저의 常缩成 제。','이것은 제 책이에요.','结构：所属者+의+事物，相当于中文“的”。\n口语中 의 常接近 [에]。\n常用缩略：저의→제，나의→내，너의→네。\n关系明确时 의 有时可以省略。','제 이름은 코코예요.\n친구의 책이에요.']];
const qs=[['review','唤醒记忆','复习到期词'],['input','听力输入','听写 3 句'],['pattern','句型替换','替换 5 组'],['output','口语输出','跟读 5 句'],['mistake','错误归档','记录错因']];
let idx=0,flip=false,listenIdx=0,speakIdx=0,detailIdx=0,scores=JSON.parse(localStorage.getItem('hanstep-progress')||'{}'),xp=Number(localStorage.getItem('hanstep-xp')||0),done=JSON.parse(localStorage.getItem('hanstep-quests')||'{}'),favorites=JSON.parse(localStorage.getItem('malbit-favorites')||'[]');
function save(){localStorage.setItem('hanstep-progress',JSON.stringify(scores));localStorage.setItem('hanstep-xp',String(xp));localStorage.setItem('hanstep-quests',JSON.stringify(done));localStorage.setItem('malbit-favorites',JSON.stringify(favorites));render()}
function isFavorite(text){return favorites.some(f=>f.text===text)}
function toggleFavorite(item){const at=favorites.findIndex(f=>f.text===item.text);if(at>=0)favorites.splice(at,1);else favorites.unshift(item);save()}
function speakKorean(text,rate=0.9){if(!('speechSynthesis'in window))return alert('当前浏览器不支持语音播放');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=rate;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase().startsWith('ko'))||null;speechSynthesis.speak(u)}
function render(){const c=cards[idx],m=Object.entries(scores).filter(([k,v])=>!k.startsWith('_')&&v>=3).length,p=Math.round(m/cards.length*100);document.querySelector('#tag').textContent=flip?'拆开记':c[4];document.querySelector('#ko').textContent=flip?c[1]:c[0];document.querySelector('#pronunciation').textContent=`实际读音 [${sounds[idx][0]}]`;document.querySelector('#hint').textContent=flip?`${c[2]} · 例句：${c[3]}`:'点击查看记忆线索';document.querySelector('#soundRule').innerHTML=`<b>发音提示</b><span>${sounds[idx][1]}</span>`;document.querySelector('#wordFavorite').textContent=isFavorite(c[3])?'♥ 已收藏':'♡ 收藏例句';document.querySelector('#count').textContent=`${idx+1} / ${cards.length}`;document.querySelector('#mastered').textContent=m;document.querySelector('#progressText').textContent=`24 个起步词 · ${p}%`;document.querySelector('#ring').style.setProperty('--progress',p*3.6+'deg');document.querySelector('#status').textContent=`Lv.${Math.floor(xp/200)+1} · ${xp} XP`;document.querySelector('#listenCount').textContent=scores._listen||0;document.querySelector('#speakCount').textContent=scores._speak||0;document.querySelector('#quests').innerHTML=qs.map(q=>`<button data-q="${q[0]}" class="${done[q[0]]?'done':''}"><span class="check">${done[q[0]]?'✓':''}</span><div><h3>${q[1]}</h3><small>${q[2]} · +20 XP</small></div></button>`).join('');document.querySelector('#stars').textContent=`${Object.values(done).filter(Boolean).length} / 5 完成`;document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const k=b.dataset.q;if(!done[k])xp+=20;done[k]=!done[k];save()});renderListen();renderSpeak();renderFavorites()}
function renderListen(){const p=phrases[listenIdx];document.querySelector('#listenNo').textContent=String(listenIdx+1).padStart(2,'0');document.querySelector('#listenKorean').textContent=p[0];document.querySelector('#listenMeaning').textContent=p[1];document.querySelector('#listenAnswer').hidden=true;document.querySelector('#dictationFeedback').textContent='';document.querySelector('#listenFavorite').textContent=isFavorite(p[0])?'♥ 已收藏':'♡ 收藏这句话'}
function renderSpeak(){const p=phrases[speakIdx];document.querySelector('#speakScene').textContent=p[2];document.querySelector('#speakKorean').textContent=p[0];document.querySelector('#speakMeaning').textContent=p[1];document.querySelector('#speakFavorite').textContent=isFavorite(p[0])?'♥ 已收藏':'♡ 收藏';document.querySelector('#scoreOrb').hidden=true}
function renderFavorites(){const box=document.querySelector('#favoritesGrid');box.innerHTML=favorites.length?favorites.map((f,i)=>`<article><span>${f.type}</span><h2>${f.text}</h2><p>${f.meaning||''}</p><div><button data-fav-speak="${i}">🔊 发音</button><button data-fav-remove="${i}">移除</button></div></article>`).join(''):'<div class="empty-favorites">还没有收藏。遇到想反复说的句子，点一下 ♡ 就会出现在这里。</div>';box.querySelectorAll('[data-fav-speak]').forEach(b=>b.onclick=()=>speakKorean(favorites[Number(b.dataset.favSpeak)].text));box.querySelectorAll('[data-fav-remove]').forEach(b=>b.onclick=()=>{favorites.splice(Number(b.dataset.favRemove),1);save()})}
function normalizeKorean(s){return s.replace(/[\s.,!?，。！？]/g,'').toLowerCase()}
document.querySelectorAll('[data-view-link],[data-go]').forEach(b=>b.onclick=e=>{e.preventDefault();const id=b.dataset.viewLink||b.dataset.go;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view-link]').forEach(n=>n.classList.toggle('active',n.dataset.viewLink===id));document.querySelector('#sidebar').classList.remove('open');location.hash=id;window.scrollTo(0,0)});
document.querySelector('#menuButton').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#card').onclick=()=>{flip=!flip;render()};document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.rate);scores[cards[idx][0]]=v;xp+=(v+1)*3;idx=(idx+1)%cards.length;flip=false;save()});document.querySelector('#reset').onclick=()=>{if(confirm('确定重置所有学习进度吗？')){scores={};xp=0;done={};save()}};
document.querySelector('#wordVoice').onclick=()=>speakKorean(cards[idx][0],.78);document.querySelector('#wordFavorite').onclick=()=>toggleFavorite({type:'单词例句',text:cards[idx][3],meaning:cards[idx][1]});
document.querySelector('#playNormal').onclick=()=>speakKorean(phrases[listenIdx][0],.9);document.querySelector('#playSlow').onclick=()=>speakKorean(phrases[listenIdx][0],.68);document.querySelector('#revealListen').onclick=()=>document.querySelector('#listenAnswer').hidden=false;document.querySelector('#paperDone').onclick=()=>{scores._listen=(scores._listen||0)+1;xp+=10;document.querySelector('#listenAnswer').hidden=false;document.querySelector('#dictationFeedback').textContent='✓ 已记录。圈出错处，再跟读三遍。';save()};document.querySelector('#listenFavorite').onclick=()=>toggleFavorite({type:'听力句子',text:phrases[listenIdx][0],meaning:phrases[listenIdx][1]});document.querySelector('#nextListen').onclick=()=>{listenIdx=(listenIdx+1)%phrases.length;renderListen()};
document.querySelector('#modelVoice').onclick=()=>speakKorean(phrases[speakIdx][0],.86);document.querySelector('#nextSpeak').onclick=()=>{speakIdx=(speakIdx+1)%phrases.length;renderSpeak()};document.querySelectorAll('[data-speech-rate]').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.speechRate);scores._speak=(scores._speak||0)+1;xp+=v*5;document.querySelector('#speechFeedback').textContent=v===3?'太好了。现在尝试不看文字再说一次。':'已记录。再听一次，重点模仿整句的节奏。';save()});
document.querySelector('#speakFavorite').onclick=()=>toggleFavorite({type:'口语句子',text:phrases[speakIdx][0],meaning:phrases[speakIdx][1]});
function editDistance(a,b){const d=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;document.querySelector('#recordVoice').onclick=()=>{if(!Recognition){document.querySelector('#speechFeedback').textContent='当前浏览器暂不支持自动评分。可使用下方自评，iOS Safari 对韩语语音识别支持可能有限。';return}const r=new Recognition();r.lang='ko-KR';r.interimResults=false;const btn=document.querySelector('#recordVoice'),wave=document.querySelector('#wave');btn.classList.add('active');btn.textContent='● 正在听你说…';wave.classList.add('active');r.onresult=e=>{const heard=e.results[0][0].transcript,goal=normalizeKorean(phrases[speakIdx][0]),actual=normalizeKorean(heard),score=Math.max(0,Math.round((1-editDistance(goal,actual)/Math.max(goal.length,actual.length,1))*100)),message=`识别到：${heard}。${score>=90?'非常清楚，试试加快到自然语速。':score>=70?'整体不错，重点检查不同的音节。':'先听慢速示范，再逐小句模仿。'}`;scores._speak=(scores._speak||0)+1;scores._bestSpeech=Math.max(scores._bestSpeech||0,score);xp+=Math.max(5,Math.round(score/8));save();document.querySelector('#speechScore').textContent=score;document.querySelector('#scoreOrb').hidden=false;document.querySelector('#speechFeedback').textContent=message};r.onerror=()=>document.querySelector('#speechFeedback').textContent='没有听清。请确认麦克风权限，靠近一些再试。';r.onend=()=>{btn.classList.remove('active');btn.textContent='● 开始跟读并评分';wave.classList.remove('active')};r.start()};
document.querySelector('#patternGrid').innerHTML=patterns.map((p,i)=>`<article data-pattern="${i}" tabindex="0"><span>0${i+1}</span><h2>${p[0]}</h2><b>${p[1]}</b><p>${p[2]}</p><blockquote>${p[3]}</blockquote><small>点击查看详细讲解 →</small></article>`).join('');
function openPattern(i){detailIdx=i;const p=patterns[i];document.querySelector('#detailTitle').textContent=p[0];document.querySelector('#detailMeaning').textContent=p[1];document.querySelector('#detailBody').innerHTML=`<h3>怎么使用</h3>${p[4].split('\n').map(x=>`<p>${x}</p>`).join('')}<h3>更多例句</h3>${p[5].split('\n').map(x=>`<blockquote>${x}</blockquote>`).join('')}`;document.querySelector('#patternFavorite').textContent=isFavorite(p[3])?'♥ 已收藏':'♡ 收藏例句';document.querySelector('#patternBackdrop').hidden=false}
document.querySelectorAll('[data-pattern]').forEach(a=>{a.onclick=()=>openPattern(Number(a.dataset.pattern));a.onkeydown=e=>{if(e.key==='Enter')openPattern(Number(a.dataset.pattern))}});document.querySelector('#patternClose').onclick=()=>document.querySelector('#patternBackdrop').hidden=true;document.querySelector('#patternBackdrop').onclick=e=>{if(e.target.id==='patternBackdrop')e.currentTarget.hidden=true};document.querySelector('#patternFavorite').onclick=()=>{const p=patterns[detailIdx];toggleFavorite({type:'语法例句',text:p[3],meaning:p[1]});document.querySelector('#patternFavorite').textContent=isFavorite(p[3])?'♥ 已收藏':'♡ 收藏例句'};
const initial=location.hash.slice(1);if(initial&&document.querySelector(`#${initial}`))document.querySelector(`[data-view-link="${initial}"]`)?.click();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
