const pronunciationNotes={
 '학교':['학꾜','紧音化：收音 ㄱ 后的 ㄱ 变成紧音 ㄲ。'], '대학교':['대학꾜','학교 部分发生紧音化，读作 [학꾜]。'], '학생회관':['학쌩회관','학생 中 ㅅ 紧音化为 ㅆ；회 常接近 [훼]。'],
 '책상':['책쌍','收音 ㄱ 后的 ㅅ 紧音化为 ㅆ。'], '쓰레기통':['쓰레기통','无特殊音变，통 的 ㅇ 收音用鼻腔结束。'], '공책':['공책','无特殊音变；책 的 ㄱ 收音只收住，不读出“克”。'],
 '연필':['연필','ㄴ、ㄹ 收音都短促，不额外添加元音。'], '읽다':['익따','겹받침 ㄺ 在这里读 ㄱ，后面的 ㄷ 紧音化。'], '학생 식당':['학쌩 식땅','학생 的 ㅅ、식당 的 ㄷ 都发生紧音化。'],
 '젓가락':['젇까락','젓 的收音中和为 ㄷ，后面的 ㄱ 紧音化为 ㄲ。'], '숟가락':['숟까락','收音 ㄷ 后面的 ㄱ 紧音化为 ㄲ。'], '숙제':['숙쩨','收音 ㄱ 后的 ㅈ 紧音化为 ㅉ。'],
 '복습하다':['복쓰파다','복습 中 ㅅ 紧音化；습+하 发生送气，接近 [쓰파]。'], '질문하다':['질문하다','无特殊音变，ㄹ 与 ㄴ 收音要短促。'], '없어요':['업써요','ㅄ 在元音前拆分，ㅅ 连到后面并读紧音。']
};
const registerLessons=[
 {title:'“在哪里”也有不同礼貌等级',rows:[['正式敬语','어디에 있습니까?','课堂发表、正式采访'],['日常敬语','어디에 있어요?','对老师、陌生人、一般社交'],['亲近语','어디에 있어?','同龄好友或晚辈'],['主体敬语','선생님은 어디에 계세요?','主语是需要尊敬的人，用 계시다 代替 있다']],tip:'初学阶段默认使用 -아요/어요 最安全；不是所有“敬语”都只改句尾，尊敬主语时词本身也可能变化。'},
 {title:'“有什么”从正式到亲近',rows:[['正式敬语','무엇이 있습니까?','正式场合'],['日常敬语','뭐가 있어요?','最常用'],['亲近语','뭐가 있어?','朋友之间'],['更尊重对方','무엇이 있으세요?','询问对方拥有的东西']],tip:'뭐 是 무엇 的口语缩略；가 是 이/가 的选择，并不是敬语标记。'},
 {title:'陈述和请求要分开看',rows:[['正式陈述','연필이 없습니다.','正式说明“没有铅笔”'],['日常敬语','연필이 없어요.','一般礼貌表达'],['亲近语','연필이 없어.','朋友之间'],['礼貌请求','아래를 보세요.','请看下面；-(으)세요 带有礼貌请求']],tip:'없어요 的语体变化在句尾；보세요 还包含“请您做”的功能，不能只翻成普通陈述。'},
 {title:'请求与许可的语体差异',rows:[['正式请求','보여 주십시오.','公告、军队或非常正式'],['日常敬语','보여 주세요.','日常最自然的礼貌请求'],['亲近语','보여 줘.','亲近关系'],['正式询问','빌릴 수 있습니까?','正式询问能否借']],tip:'주세요 不只是“给我”，接在动词 -아/어 后表示“请为我做……”。'},
 {title:'想吃与尊敬对方',rows:[['正式陈述','먹고 싶습니다.','正式表达自己的愿望'],['日常敬语','먹고 싶어요.','日常表达'],['亲近语','먹고 싶어.','朋友之间'],['尊敬询问','뭐 드시고 싶으세요?','问长辈想吃什么；드시다 是 먹다 的敬语词']],tip:'不能对自己的动作使用主体敬语。说自己想吃用 먹고 싶어요，不用 드시다。'},
 {title:'提议的语气与关系',rows:[['正式提议','같이 공부하시겠습니까?','非常正式地邀请'],['日常敬语','같이 공부할까요?','自然地提议“一起学好吗”'],['亲近语','같이 공부할까?','朋友之间'],['约定表达','도서관에서 만나요.','礼貌地说“图书馆见”']],tip:'-(으)ㄹ까요? 语调上扬表示征求意见；降调有时像在自问或推测。'}
];

function currentStoryDay(){const i=storyLessons.findIndex((_,n)=>!storyPassed(n+1));return i<0?6:i+1}
function lessonWords(day=currentStoryDay()){return storyLessons[day-1].words}
function wordDetail(word,meaning,day=currentStoryDay()){const note=pronunciationNotes[word]||[word,'本词没有必须改变拼写的特殊音变，先按音节稳定发音。'];return {word,meaning,pron:note[0],rule:note[1],memory:`把它放回第 ${day} 课“小澄${storyLessons[day-1].title.replace('小澄','')}”的画面中记；不要脱离课文单背。`,example:storyLessons[day-1].dialogue.find(x=>x[1].includes(word.replace('하다','')))?.[1]||`${word} — ${meaning}`}}
function ensureMemory(){courseState.memory=courseState.memory||{};storyLessons.forEach((l,li)=>{if(li+1>currentStoryDay()&&!storyPassed(li+1))return;l.words.forEach(([w])=>courseState.memory[w]=courseState.memory[w]||{due:0,interval:0,lapses:0,seen:0})})}
function saveMemory(){localStorage.setItem('malbit-course',JSON.stringify(courseState));window.dispatchEvent(new Event('malbit-progress-changed'))}
function dueWords(){ensureMemory();const now=Date.now(),allowed=storyLessons.slice(0,currentStoryDay()).flatMap((l,i)=>l.words.map(w=>[w,i+1]));return allowed.map(([w,day])=>wordDetail(w[0],w[1],day)).filter(x=>(courseState.memory[x.word]?.due||0)<=now).sort((a,b)=>(courseState.memory[b.word]?.lapses||0)-(courseState.memory[a.word]?.lapses||0))}

const baseStoryStage=renderStoryStage;
renderStoryStage=stage=>{baseStoryStage(stage);const l=storyLessons[activeStoryLesson-1];if(stage===1){document.querySelectorAll('.vocab-deck [data-word]').forEach((b,i)=>{const d=wordDetail(l.words[i][0],l.words[i][1],activeStoryLesson);b.innerHTML+=`<span class="word-pron">[${d.pron}]</span><span class="word-rule">${d.rule}</span><span class="word-memory">记忆：${d.memory}</span>`})}if(stage===2){const g=document.querySelector('.grammar-lessons'),r=registerLessons[activeStoryLesson-1];g.insertAdjacentHTML('beforeend',`<article class="register-class"><b>语体</b><div><h3>${r.title}</h3><div class="register-table">${r.rows.map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small><button data-register-say="${x[1]}">🔊</button></div>`).join('')}</div><p class="register-tip">注意：${r.tip}</p></div></article>`);g.querySelectorAll('[data-register-say]').forEach(b=>b.onclick=()=>speakKorean(b.dataset.registerSay,.84))}if(stage===4){const field=document.querySelector('.output-answer')?.closest('fieldset');if(field){const correct=l.output[2],wrong=[correct.replace('에 있어요','이 있어요').replace('도 있어요','가 있어요'),correct.replace('보여 주세요','보여 있어요').replace('먹고 싶어요','먹어 있어요').replace('에서 만나요','에 만나요'),correct.replace('있어요','없어요').replace('주세요','줍니다').replace('싶어요','싶습니까')].filter(x=>x&&x!==correct).slice(0,2),opts=[correct,...wrong].sort(()=>.5-Math.random());field.innerHTML=`<legend>5. ${l.output[0]}</legend><p class="stem-sentence">${l.output[1]} ___</p>${opts.map(o=>`<label><input type="radio" name="output" value="${o}">${o}</label>`).join('')}`;document.querySelector('#storyTest').onsubmit=e=>gradeStoryTest(e,l)}}};

const baseGradeStory=gradeStoryTest;
gradeStoryTest=(e,l)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(l.quiz.some((_,i)=>f.get(`sq${i}`)===null)||f.get('output')===null){document.querySelector('#storyTestResult').innerHTML='<div class="test-result retry"><b>还有题目没完成</b><span>全部选择后才能计算掌握度。</span></div>';return}let right=0,reviews=[];l.quiz.forEach((q,i)=>{const ok=Number(f.get(`sq${i}`))===q[2];right+=ok?1:0;reviews.push(`${ok?'✓':'×'} 第${i+1}题：${ok?'正确':`正确答案是“${q[1][q[2]]}”`}`)});const outputOK=f.get('output')===l.output[2];right+=outputOK?1:0;reviews.push(`${outputOK?'✓':'×'} 第5题：${outputOK?'正确':`正确答案是“${l.output[2]}”`}`);const score=right*20;courseState.lessonScores=courseState.lessonScores||{};courseState.lessonScores[storyKey(activeStoryLesson)]=Math.max(score,courseState.lessonScores[storyKey(activeStoryLesson)]||0);ensureMemory();const delay=score>=80?864e5:36e5;l.words.forEach(([w])=>{const m=courseState.memory[w];m.due=Date.now()+delay;if(score<80)m.lapses++});if(score>=80){courseState.lessonDone[storyKey(activeStoryLesson)]=true;courseState.day=activeStoryLesson+1}saveMemory();renderCourse();const result=document.querySelector('#storyTestResult');result.innerHTML=`<div class="test-result ${score>=80?'pass':'retry'}"><strong>${score}</strong><div><b>${score>=80?'本课已掌握，下一段故事已解锁':'尚未掌握，1 小时后会再次复习本课词汇'}</b><span>答对 ${right}/5 · 掌握线 80 分</span></div></div><div class="test-reviews">${reviews.map(x=>`<p>${x}</p>`).join('')}</div><button id="storyResultAction">${score>=80?(activeStoryLesson<6?'进入下一课 →':'进入单元结业考 →'):'回到词汇与语法复习'}</button>`;e.currentTarget.hidden=true;document.querySelector('#storyResultAction').onclick=()=>score<80?renderStoryStage(1):activeStoryLesson<6?openStoryLesson(activeStoryLesson+1):(document.querySelector('#lessonBackdrop').hidden=true,document.querySelector('[data-view-link="exam"]').click(),renderExamByUnit())};

let courseWordIndex=0,courseListenIndex=0,courseSpeakIndex=0;
function reviewQueue(){const due=dueWords();return due.length?due:lessonWords().map(w=>wordDetail(w[0],w[1]))}
function renderCourseWord(){const q=reviewQueue(),d=q[courseWordIndex%q.length],m=courseState.memory[d.word]||{};document.querySelector('#tag').textContent=`第 ${currentStoryDay()} 课 · ${m.lapses?'重点返场':'课程词汇'}`;document.querySelector('#ko').textContent=d.word;document.querySelector('#pronunciation').textContent=`实际读音 [${d.pron}]`;document.querySelector('#hint').textContent=flip?`${d.meaning} · ${d.memory} · 课文：${d.example}`:'先读出来，再点击查看记忆线索';document.querySelector('#soundRule').innerHTML=`<b>发音与音变</b><span>${d.rule}</span>`;document.querySelector('#count').textContent=`今日待复习 ${dueWords().length} · 本轮 ${courseWordIndex%q.length+1}/${q.length}`;document.querySelector('#wordVoice').onclick=()=>speakKorean(d.word,.78);document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rateCourseWord(d,Number(b.dataset.rate)))}
function rateCourseWord(d,rating){const m=courseState.memory[d.word]||{interval:0,lapses:0,seen:0};m.seen++;if(rating===0){m.lapses++;m.interval=0;m.due=Date.now()+6e5}else if(rating===1){m.lapses++;m.interval=0;m.due=Date.now()+4*36e5}else if(rating===2){m.interval=Math.max(1,m.interval||1);m.due=Date.now()+m.interval*864e5}else{m.interval=Math.max(3,(m.interval||1)*2);m.due=Date.now()+m.interval*864e5}courseState.memory[d.word]=m;courseState.today.reviewed++;courseWordIndex++;flip=false;saveMemory();render()}
function currentPhrases(){return storyLessons[currentStoryDay()-1].dialogue.map(x=>[x[1],x[2],`${storyLessons[currentStoryDay()-1].title} · ${x[0]}`])}
function renderCourseListen(){const ps=currentPhrases(),p=ps[courseListenIndex%ps.length];document.querySelector('#listenNo').textContent=`课${currentStoryDay()}-${courseListenIndex%ps.length+1}`;document.querySelector('#listenKorean').textContent=p[0];document.querySelector('#listenMeaning').textContent=p[1];document.querySelector('#listenAnswer').hidden=true;document.querySelector('#dictationFeedback').textContent='';document.querySelector('#playNormal').onclick=()=>speakKorean(p[0],.88);document.querySelector('#playSlow').onclick=()=>speakKorean(p[0],.7);document.querySelector('#revealListen').onclick=()=>document.querySelector('#listenAnswer').hidden=false;document.querySelector('#nextListen').onclick=()=>{courseListenIndex++;renderCourseListen()};document.querySelector('#paperDone').onclick=()=>{courseState.today.listened++;saveMemory();document.querySelector('#listenAnswer').hidden=false;document.querySelector('#dictationFeedback').textContent='✓ 已记录到当前课程的听力练习。';renderHomePlan()}}
function renderCourseSpeak(){const ps=currentPhrases(),p=ps[courseSpeakIndex%ps.length];document.querySelector('#speakScene').textContent=p[2];document.querySelector('#speakKorean').textContent=p[0];document.querySelector('#speakMeaning').textContent=p[1];document.querySelector('#scoreOrb').hidden=true;document.querySelector('#modelVoice').onclick=()=>speakKorean(p[0],.84);document.querySelector('#nextSpeak').onclick=()=>{courseSpeakIndex++;renderCourseSpeak()};document.querySelectorAll('[data-speech-rate]').forEach(b=>b.onclick=()=>{courseState.today.spoken++;saveMemory();document.querySelector('#speechFeedback').textContent=Number(b.dataset.speechRate)>=2?'已记录到本课口语练习。明天会再次抽取薄弱句。':'这句会留在今日任务里，请再听两遍后重试。';renderHomePlan()})}
function renderCoursePatterns(){const l=storyLessons[currentStoryDay()-1],r=registerLessons[currentStoryDay()-1],box=document.querySelector('#patternGrid');box.innerHTML=l.grammar.map((g,i)=>`<article><span>0${i+1}</span><small>第 ${currentStoryDay()} 课同步语法</small><h2>${g[0]}</h2><p>${g[1]}</p><blockquote>${g[2]}</blockquote><button data-pattern-say="${g[2]}">🔊 听例句</button></article>`).join('')+`<article class="register-map"><span>语体</span><small>敬语与普通语</small><h2>${r.title}</h2>${r.rows.map(x=>`<p><b>${x[0]}</b> ${x[1]}<br><small>${x[2]}</small></p>`).join('')}<blockquote>${r.tip}</blockquote></article>`;box.querySelectorAll('[data-pattern-say]').forEach(b=>b.onclick=()=>speakKorean(b.dataset.patternSay,.84))}
function todayState(){const date=new Date().toLocaleDateString('sv-SE');courseState.today=courseState.today?.date===date?courseState.today:{date,reviewed:0,listened:0,spoken:0};return courseState.today}
function renderHomePlan(){const t=todayState(),due=dueWords().length,day=currentStoryDay(),mistakes=mistakeState.filter(m=>!m.reviewed).length,tasks=[['learn',`复习 ${due} 个到期词`,t.reviewed>0,`根据遗忘时间自动安排${due?'，先处理最容易忘的词':''}`],['course',`继续第 ${day} 课故事`,storyPassed(day),'课文、词汇、音变、语法在同一课堂'],['listen','完成本课听辨',t.listened>0,'只抽取当前课程课文原句'],['speak','完成本课跟读',t.spoken>0,'跟读当前课文并记录表现'],['mistakes',`修复 ${mistakes} 个错点`,mistakes===0,'错题和记不牢内容持续返场']];const box=document.querySelector('#quests');box.innerHTML=tasks.map(x=>`<button data-plan-go="${x[0]}" class="${x[2]?'done':''}"><span class="check">${x[2]?'✓':'→'}</span><div><h3>${x[1]}</h3><small>${x[3]}</small></div></button>`).join('');box.querySelectorAll('[data-plan-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-view-link="${b.dataset.planGo}"]`).click());document.querySelector('#stars').textContent=`${tasks.filter(x=>x[2]).length} / 5 今日任务完成`;document.querySelector('.today-card h2').innerHTML=`先复习快忘的，<br>再继续第 ${day} 课。`;document.querySelector('.today-card [data-go]').textContent=due?'先开始到期复习 →':`继续第 ${day} 课 →`;document.querySelector('.today-card [data-go]').dataset.go=due?'learn':'course'}
function syncCourseTools(){ensureMemory();todayState();renderCourseWord();renderCourseListen();renderCourseSpeak();renderCoursePatterns();renderHomePlan();const total=Object.keys(courseState.memory).length,mastered=Object.values(courseState.memory).filter(x=>x.interval>=3).length;document.querySelector('#mastered').textContent=mastered;document.querySelector('#progressText').textContent=`课程词汇 ${total} 个 · 稳定记住 ${mastered} 个`;document.querySelector('#ring').style.setProperty('--progress',(total?mastered/total*360:0)+'deg');document.querySelector('#listenCount').textContent=courseState.today.listened;document.querySelector('#speakCount').textContent=courseState.today.spoken}
const legacyAppRender=render;render=()=>{legacyAppRender();syncCourseTools()};render();
