const courseUnits=[
 {n:1,title:'相遇与自我介绍',days:7,goal:'不看稿完成 30 秒自我介绍，并听懂姓名、国籍和职业',skills:['身份词汇 45 个','이에요/예요、은/는','问候与自我介绍听力','30 秒口头输出'],gate:'第一单元诊断'},
 {n:2,title:'学校与学习生活',days:7,goal:'介绍学校场所、物品和自己的学习安排',skills:['校园词汇 55 个','이/가 있어요、에','位置与物品听力','描述自己的书桌'],gate:'光阶 2 门槛'},
 {n:3,title:'家人与朋友',days:7,goal:'介绍家庭成员、年龄和人物关系',skills:['人物词汇 60 个','하고/와/과、도','人物信息听辨','介绍一位家人'],gate:'单元小考'},
 {n:4,title:'饮食与点餐',days:7,goal:'看懂基础菜单并完成一次点餐对话',skills:['饮食词汇 70 个','주세요、을/를','价格与点餐听力','完成点餐角色扮演'],gate:'光阶 3 门槛'},
 {n:5,title:'一天的生活',days:7,goal:'用韩语描述一天，并听懂时间安排',skills:['日常动作 70 个','아요/어요、부터/까지','时间与作息听力','1 分钟作息表达'],gate:'单元小考'},
 {n:6,title:'购物与数量',days:7,goal:'询价、选择商品并表达数量',skills:['商品与数词 80 个','몇、 얼마예요','数字价格听辨','购物情景对话'],gate:'光阶 4 门槛'},
 {n:7,title:'交通与出行',days:7,goal:'询问路线、理解方向并说明出行方式',skills:['交通词汇 70 个','에서/까지、으로','路线信息听力','问路与指路'],gate:'单元小考'},
 {n:8,title:'电话与约定',days:7,goal:'完成简短电话沟通并约定时间地点',skills:['约会词汇 65 个','(으)ㄹ까요、고 싶어요','电话关键信息','邀请与回应'],gate:'光阶 5 门槛'},
 {n:9,title:'天气与季节',days:7,goal:'谈论天气、季节和适合的活动',skills:['天气词汇 60 个','지만、아서/어서','天气预报听力','表达偏好与原因'],gate:'单元小考'},
 {n:10,title:'假日与计划',days:7,goal:'讲述过去经历并制定简单计划',skills:['旅行词汇 80 个','았/었어요、(으)ㄹ 거예요','行程听力','90 秒经历与计划'],gate:'第一册结业考'}
];
const lightLevels=[
 ['光阶 1 · 初见','能读韩文并完成固定问候','TOPIK 1 起步'],['光阶 2 · 开口','能介绍自己、学校与身边物品','TOPIK 1 前段'],['光阶 3 · 日常','能应对家庭、饮食和作息话题','TOPIK 1 中段'],['光阶 4 · 行动','能完成购物、时间和数量沟通','TOPIK 1 后段'],['光阶 5 · 连接','能问路、约定并表达简单原因','TOPIK 2 起步'],['光阶 6 · 独立','完成第一册，能处理基础生活对话','TOPIK 2 前段']
];
const dailyLessons={
  1:[['身份词汇唤醒','复习 저、제、사람、학생、선생님、친구、의사、회사원','看到中文后 3 秒内说出韩语；正确率达到 90%'],['이에요/예요','学习有收音用 이에요、无收音用 예요，并与 아니에요 对照','完成 10 次替换，至少 9 次正确'],['自我介绍发音','练习 학생[학쌩]、맞아요[마자요] 和句尾自然语调','听辨 6 组并跟读，每句连续说顺 3 次'],['身份信息听力','只听声音辨认姓名、国籍、职业三类信息','两遍内抓住 3 个关键信息'],['30 秒自我介绍','组合问候、姓名、国籍、身份和正在学习的内容','脱稿说满 4 句，不停顿超过 3 秒'],['混合复习','把词汇、句型、听力和口语随机混合','综合练习达到 85%'],['第一单元诊断','完成词汇、语法、发音、理解和输出考核','总分达到 80%，错题全部完成一次修复']],
  2:[['校园与物品词汇','学习 학교、교실、도서관、책、책상、의자、가방、연필 等核心词','看图或中文 3 秒内说出，正确率 85%'],['存在表达','掌握 N이/가 있어요/없어요，区分有收音和无收音','用自己的房间或书桌造 8 句'],['位置表达','学习 앞、뒤、옆、위、아래、안 和 N에 있어요','看位置图连续说对 6 题'],['校园听力','听懂“什么在哪里”和“有没有某物”','正常语速两遍内答对 4/5'],['描述我的书桌','把物品词、位置词和 있어요 连起来','脱稿说出至少 5 句'],['问答闭环','练习 뭐가 있어요? / 어디에 있어요?','完成 5 轮完整问答'],['第二单元结业考','词汇 25% + 语法 25% + 听力 25% + 输出 25%','总分 80%，且任何单项不低于 60%']]
};
const unitOneQuiz=[
 {type:'词汇',q:'“老师”的韩语是哪一个？',opts:['학생','선생님','친구','회사원'],a:1,why:'선생님 = 老师；님 是尊称。'},
 {type:'语法',q:'选择正确句子：我是学生。',opts:['저는 학생예요.','저가 학생이에요.','저는 학생이에요.','저는 학생이 아니에요.'],a:2,why:'학생有收音，所以使用 이에요；介绍主题用 저는。'},
 {type:'语法',q:'의사 后应接哪一个？',opts:['이에요','예요','은','을'],a:1,why:'의사 没有收音，使用 예요。'},
 {type:'理解',q:'“어느 나라 사람이에요?” 在问什么？',opts:['叫什么名字','是哪国人','做什么工作','去哪所学校'],a:1,why:'어느 나라=哪个国家，사람=人。'},
 {type:'发音',q:'학생 的实际读音更接近：',opts:['[학생]','[학쌩]','[항생]','[하생]'],a:1,why:'받침 ㄱ 后的 ㅅ 紧音化为 ㅆ。'},
 {type:'输出',q:'自我介绍中，“我的名字是 Coco”应选择：',opts:['제 이름은 코코예요.','저 이름이 코코이에요.','제 이름를 코코예요.','저는 이름 코코예요.'],a:0,why:'저의 缩略为 제；이름 有收音，作话题用 은。'}
];
const unitTwoQuiz=[
 {type:'词汇',q:'“图书馆”的韩语是哪一个？',opts:['교실','도서관','책상','학교'],a:1,why:'도서관 = 图书馆；교실是教室，책상是书桌。'},
 {type:'语法',q:'选择正确句子：有一本书。',opts:['책가 있어요.','책이 있어요.','책을 있어요.','책은 없어요.'],a:1,why:'책有收音，作存在句的主语时使用 이：책이 있어요。'},
 {type:'语法',q:'“朋友在教室里”正确的是：',opts:['친구가 교실에 있어요.','친구를 교실이 있어요.','친구에 교실가 있어요.','교실을 친구가 있어요.'],a:0,why:'存在的人用 이/가 标记；存在地点用 에 标记。'},
 {type:'位置',q:'책상 위에 연필이 있어요. 是什么意思？',opts:['铅笔在书桌下面','铅笔在书桌上面','书桌在铅笔旁边','书桌上没有铅笔'],a:1,why:'위 表示上面；N 위에 表示“在 N 上面”。'},
 {type:'发音',q:'학교 的实际读音更接近：',opts:['[학교]','[항교]','[학꾜]','[하교]'],a:2,why:'받침 ㄱ 后的 ㄱ 发生紧音化，학교 读作 [학꾜]。'},
 {type:'输出',q:'询问“书在哪里？”应选择：',opts:['책이 뭐예요?','책이 어디에 있어요?','책을 있어요?','어디가 책이에요?'],a:1,why:'询问位置使用 어디에 있어요?，主语 책 有收音所以接 이。'}
];
const unitTwoMaterial={
 1:{title:'校园与物品词汇',intro:'今天先建立能用来描述学习空间的核心词汇。点击发音，跟读后完成下方小练习。',sections:[['核心场所','학교 学校 · 교실 教室 · 도서관 图书馆 · 식당 食堂'],['核心物品','책 书 · 책상 书桌 · 의자 椅子 · 가방 书包 · 연필 铅笔 · 공책 笔记本'],['发音重点','학교 → [학꾜]：ㄱ 后的 ㄱ 紧音化；책 的末尾 ㄱ 只收住，不加“克”。']],practice:{q:'“教室”的韩语是？',opts:['학교','교실','도서관'],a:1}},
 2:{title:'存在表达：이/가 있어요',intro:'있어요 表示“有”或“存在”。先确定谁存在，再根据名词有没有收音选择 이/가。',sections:[['接续规则','有收音 + 이：책이 있어요. 有书。'],['接续规则','无收音 + 가：의자가 있어요. 有椅子。'],['否定表达','없어요 表示“没有”：책이 없어요. 没有书。']],practice:{q:'“有书包”正确的是？',opts:['가방가 있어요.','가방이 있어요.','가방을 있어요.'],a:1}},
 3:{title:'位置表达：N에 있어요',intro:'地点后加 에，表达某人或某物在哪里。结构是“对象 + 이/가 + 地点 + 에 있어요”。',sections:[['位置词','앞 前面 · 뒤 后面 · 옆 旁边 · 위 上面 · 아래 下面 · 안 里面'],['完整结构','책이 가방 안에 있어요. 书在包里面。'],['提问方式','어디에 있어요? 在哪里？']],practice:{q:'“铅笔在书桌上”正确的是？',opts:['연필이 책상 위에 있어요.','연필을 책상 위가 있어요.','책상이 연필에 있어요.'],a:0}},
 4:{title:'校园听力',intro:'先听句子，不看文字判断关键信息；再展开原文核对主语和地点。',sections:[['听力策略','第一遍只抓“什么”；第二遍抓“在哪里”；不要试图逐字翻译。'],['练习句','책이 가방 안에 있어요.'],['核对问题','什么东西？在哪里？答案：书，在包里面。']],practice:{q:'句中 책 在哪里？',opts:['가방 안','책상 위','교실 앞'],a:0},audio:'책이 가방 안에 있어요.'},
 5:{title:'描述我的书桌',intro:'把物品、位置和 있어요 组合成可以真正说出口的句子。',sections:[['句子模板','책상 위에 ___이/가 있어요. 书桌上有……'],['示范输出','책상 위에 책하고 연필이 있어요. 책상 옆에 가방이 있어요.'],['你的任务','看自己的书桌，至少说 5 句；同一物品不要重复。']],practice:{q:'选择最自然的描述：',opts:['책상 위에 책이 있어요.','책상 책을 위 있어요.','책이 위를 책상이에요.'],a:0}},
 6:{title:'问答闭环',intro:'今天不增加新知识，把“有什么、在哪里”练成无需翻译就能回答的反射。',sections:[['问物品','뭐가 있어요? 有什么？— 책이 있어요.'],['问位置','책이 어디에 있어요? 书在哪里？— 가방 안에 있어요.'],['闭环任务','连续完成 5 轮问答，每次替换物品和位置。']],practice:{q:'对“뭐가 있어요?”最合适的回答：',opts:['책이 있어요.','책이 어디예요?','가방 안에요?'],a:0}}
};
let courseState=JSON.parse(localStorage.getItem('malbit-course')||'{}');
courseState={unit:1,day:1,passed:{},lessonDone:{},...courseState,passed:{...(courseState.passed||{})},lessonDone:{...(courseState.lessonDone||{})}};
let mistakeState=JSON.parse(localStorage.getItem('malbit-mistakes')||'[]');
if(!Array.isArray(mistakeState))mistakeState=[];
let quizAnswers={};
function persistCourse({rerenderExam=true}={}){localStorage.setItem('malbit-course',JSON.stringify(courseState));localStorage.setItem('malbit-mistakes',JSON.stringify(mistakeState));renderCourse();if(rerenderExam)renderExam();renderMistakes();window.dispatchEvent(new Event('malbit-progress-changed'))}
function currentLight(){const passed=Object.keys(courseState.passed||{}).filter(k=>courseState.passed[k]>=80).length;return Math.min(6,1+Math.floor(passed/2))}
function renderCourse(){const level=currentLight(),unit=courseUnits[Math.max(0,(courseState.unit||1)-1)],day=Math.min(7,courseState.day||1),lesson=(dailyLessons[unit.n]||[])[day-1]||['本日综合能力课',`围绕“${unit.title}”完成词汇、句型、听力和口语闭环`,unit.goal];document.querySelector('#courseDashboard').innerHTML=`
 <div class="ability-card"><div><span>全程 30 光阶 · 每 5 光阶约对应一个 TOPIK 大等级</span><h2>${lightLevels[level-1][0]}</h2><p>${lightLevels[level-1][1]} · 约 ${lightLevels[level-1][2]}。第一册覆盖光阶 1–6。</p></div><div class="level-track">${lightLevels.map((l,i)=>`<i class="${i<level?'on':''}"></i>`).join('')}</div></div>
 <div class="course-now"><div><span>第 ${unit.n} 单元 · 第 ${day}/7 天</span><h2>${unit.title}</h2><p>本单元结业标准：${unit.goal}</p><div class="today-lesson"><small>今天的课程</small><h3>${lesson[0]}</h3><p>${lesson[1]}</p><b>今日达标：${lesson[2]}</b></div><h3>本单元必须掌握</h3><ul>${unit.skills.map(s=>`<li>${s}</li>`).join('')}</ul><div class="lesson-actions"><button id="completeLesson">完成今日课程</button><button data-course-exam>参加${unit.gate} →</button></div></div><div class="day-path">${Array.from({length:7},(_,i)=>`<button class="${i<day?'done':''}"><b>${i+1}</b><span>${['词汇输入','核心句型','发音听辨','听力精练','口语输出','综合复习','单元考核'][i]}</span></button>`).join('')}</div></div>
 <h2 class="course-title">第一册 · 70 天路线</h2><div class="unit-grid">${courseUnits.map(u=>`<article class="${u.n==unit.n?'current':''}"><span>UNIT ${String(u.n).padStart(2,'0')} · ${u.days} 天</span><h3>${u.title}</h3><p>${u.goal}</p><b>${courseState.passed?.[u.n]?`已通过 ${courseState.passed[u.n]} 分`:u.gate}</b></article>`).join('')}</div>`;document.querySelector('#completeLesson').onclick=()=>{courseState.day=Math.min(7,(courseState.day||1)+1);courseState.lessonDone[`${unit.n}-${courseState.day-1}`]=true;persistCourse()};document.querySelector('[data-course-exam]').onclick=()=>document.querySelector('[data-view-link="exam"]').click()}
function renderExam(){const previous=courseState.passed?.[1];document.querySelector('#examCenter').innerHTML=`<div class="exam-intro"><span>第一单元诊断 · 约 8 分钟</span><h2>${previous?`上次成绩 ${previous} 分`:'先确认第一单元是否真正掌握'}</h2><p>本次基础卷包含词汇、语法、理解、发音和输出判断。达到 80 分后进入第二单元；错题会自动进入修复区。</p></div><form id="unitQuiz">${unitOneQuiz.map((x,i)=>`<fieldset><legend><span>${x.type}</span>${i+1}. ${x.q}</legend>${x.opts.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}">${o}</label>`).join('')}</fieldset>`).join('')}<button class="submit-exam">提交并评分</button></form><div id="examResult"></div>`;document.querySelector('#unitQuiz').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),missing=unitOneQuiz.findIndex((_,i)=>form.get(`q${i}`)===null);if(missing>=0){document.querySelector('#examResult').innerHTML=`<div class="result-card retry"><h2>还有题目没有回答</h2><p>请完成第 ${missing+1} 题后再提交。</p></div>`;return}let right=0;mistakeState=mistakeState.filter(m=>m.exam!=='unit-1');unitOneQuiz.forEach((x,i)=>{const picked=Number(form.get(`q${i}`));if(picked===x.a)right++;else mistakeState.push({id:`u1-${i}`,exam:'unit-1',type:x.type,q:x.q,your:x.opts[picked],answer:x.opts[x.a],why:x.why,reviewed:false})});const score=Math.round(right/unitOneQuiz.length*100);courseState.passed=courseState.passed||{};courseState.passed[1]=score;if(score>=80){courseState.unit=Math.max(2,courseState.unit||1);courseState.day=1}persistCourse({rerenderExam:false});document.querySelector('#examResult').innerHTML=`<div class="result-card ${score>=80?'pass':'retry'}"><strong>${score}</strong><h2>${score>=80?'通过！第二单元已解锁':'还差一点，先修复错题'}</h2><p>答对 ${right}/${unitOneQuiz.length} 题。${score>=80?'你的第一单元基础已达到光阶升级要求。':'错题已自动加入“错题复习”。复习后可以再次参加。'}</p></div>`;document.querySelector('#examResult').scrollIntoView({behavior:'smooth'})}}
function renderMistakes(){const pending=mistakeState.filter(m=>!m.reviewed);document.querySelector('#mistakeCenter').innerHTML=pending.length?`<div class="mistake-summary"><b>${pending.length}</b><span>个知识漏洞等待修复</span></div><div class="mistake-grid">${pending.map((m,i)=>`<article><span>${m.type}</span><h3>${m.q}</h3><p class="wrong">你的答案：${m.your}</p><p class="correct">正确答案：${m.answer}</p><details><summary>查看为什么</summary><p>${m.why}</p></details><button data-fixed="${m.id}">我已经理解</button></article>`).join('')}</div>`:'<div class="empty-favorites">目前没有待复习错题。完成单元小考后，错误会自动出现在这里。</div>';document.querySelectorAll('[data-fixed]').forEach(b=>b.onclick=()=>{const m=mistakeState.find(x=>x.id===b.dataset.fixed);if(m)m.reviewed=true;persistCourse()})}
function openLesson(dayIndex){const unit=courseUnits[Math.max(0,(courseState.unit||1)-1)],lesson=(dailyLessons[unit.n]||[])[dayIndex-1]||['综合能力课',`围绕“${unit.title}”完成输入与输出练习`,unit.goal],focus=unit.n===1?[['词汇输入','先点击“单词记忆”，完成本单元身份词汇卡。读出每个词，注意实际发音。'],['理解检查','遮住韩语，看中文能否在 3 秒内说出；把不熟的例句加入收藏。'],['主动输出','用 저는 ___이에요/예요 说 4 个不同身份句。']]:[['知识输入',lesson[1]],['跟练任务','进入对应的单词、听力或口语区，至少完成一轮练习。'],['主动输出','不用提示，完成今天要求的韩语表达。']];document.querySelector('#lessonLabel').textContent=`UNIT ${unit.n} · DAY ${dayIndex}`;document.querySelector('#lessonTitle').textContent=lesson[0];document.querySelector('#lessonLead').textContent=lesson[1];document.querySelector('#lessonContent').innerHTML=`<div class="mastery-box"><small>本课掌握标准</small><b>${lesson[2]}</b></div>${focus.map((x,i)=>`<label class="lesson-step"><input type="checkbox" value="${i}"><span><b>${i+1}. ${x[0]}</b><p>${x[1]}</p></span></label>`).join('')}`;document.querySelector('#lessonWarning').textContent='';document.querySelector('#lessonComplete').dataset.day=dayIndex;document.querySelector('#lessonBackdrop').hidden=false}
function renderCourseInteractive(){const level=currentLight(),unit=courseUnits[Math.max(0,(courseState.unit||1)-1)],day=Math.min(7,courseState.day||1),lesson=(dailyLessons[unit.n]||[])[day-1]||['本日综合能力课',`围绕“${unit.title}”完成词汇、句型、听力和口语闭环`,unit.goal];document.querySelector('#courseDashboard').innerHTML=`<div class="ability-card"><div><span>全程 30 光阶 · 每 5 光阶约对应一个 TOPIK 大等级</span><h2>${lightLevels[level-1][0]}</h2><p>${lightLevels[level-1][1]} · 约 ${lightLevels[level-1][2]}。第一册覆盖光阶 1–6。</p></div><div class="level-track">${lightLevels.map((l,i)=>`<i class="${i<level?'on':''}"></i>`).join('')}</div></div><div class="course-now"><div><span>第 ${unit.n} 单元 · 第 ${day}/7 天</span><h2>${unit.title}</h2><p>本单元结业标准：${unit.goal}</p><div class="today-lesson"><small>今天的课程</small><h3>${lesson[0]}</h3><p>${lesson[1]}</p><b>今日达标：${lesson[2]}</b></div><h3>本单元必须掌握</h3><ul>${unit.skills.map(s=>`<li>${s}</li>`).join('')}</ul><div class="lesson-actions"><button id="enterLesson">进入今天的课程 →</button><button data-course-exam>参加${unit.gate}</button></div></div><div class="day-path">${Array.from({length:7},(_,i)=>`<button data-lesson-day="${i+1}" class="${i+1<day?'done':''} ${i+1===day?'current':''}" ${i+1>day?'disabled':''}><b>${i+1}</b><span>${['词汇输入','核心句型','发音听辨','听力精练','口语输出','综合复习','单元考核'][i]}${i+1>day?' · 未解锁':''}</span></button>`).join('')}</div></div><h2 class="course-title">第一册 · 70 天路线</h2><div class="unit-grid">${courseUnits.map(u=>`<article class="${u.n==unit.n?'current':''}"><span>UNIT ${String(u.n).padStart(2,'0')} · ${u.days} 天</span><h3>${u.title}</h3><p>${u.goal}</p><b>${courseState.passed?.[u.n]?`已通过 ${courseState.passed[u.n]} 分`:u.gate}</b></article>`).join('')}</div>`;document.querySelector('#enterLesson').onclick=()=>openLesson(day);document.querySelectorAll('[data-lesson-day]').forEach(b=>b.onclick=()=>openLesson(Number(b.dataset.lessonDay)));document.querySelector('[data-course-exam]').onclick=()=>document.querySelector('[data-view-link="exam"]').click()}
function renderExamDetailed(){const previous=courseState.passed?.[1];document.querySelector('#examCenter').innerHTML=`<div class="exam-intro"><span>第一单元诊断 · 约 8 分钟</span><h2>${previous?`上次成绩 ${previous} 分`:'先确认第一单元是否真正掌握'}</h2><p>交卷后会立即逐题显示正确答案与讲解。达到 80 分后进入第二单元。</p></div><form id="unitQuiz">${unitOneQuiz.map((x,i)=>`<fieldset><legend><span>${x.type}</span>${i+1}. ${x.q}</legend>${x.opts.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}">${o}</label>`).join('')}</fieldset>`).join('')}<button class="submit-exam">提交并查看逐题解析</button></form><div id="examResult"></div>`;document.querySelector('#unitQuiz').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),missing=unitOneQuiz.findIndex((_,i)=>form.get(`q${i}`)===null),result=document.querySelector('#examResult');if(missing>=0){result.innerHTML=`<div class="result-card retry"><h2>还有题目没有回答</h2><p>请完成第 ${missing+1} 题后再提交。</p></div>`;return}let right=0;const reviews=[];mistakeState=mistakeState.filter(m=>m.exam!=='unit-1');unitOneQuiz.forEach((x,i)=>{const picked=Number(form.get(`q${i}`)),ok=picked===x.a;if(ok)right++;else mistakeState.push({id:`u1-${i}`,exam:'unit-1',type:x.type,q:x.q,your:x.opts[picked],answer:x.opts[x.a],why:x.why,reviewed:false});reviews.push({x,picked,ok})});const score=Math.round(right/unitOneQuiz.length*100);courseState.passed=courseState.passed||{};courseState.passed[1]=score;if(score>=80){courseState.unit=Math.max(2,courseState.unit||1);courseState.day=1}persistCourse({rerenderExam:false});result.innerHTML=`<div class="result-card ${score>=80?'pass':'retry'}"><strong>${score}</strong><h2>${score>=80?'通过！第二单元已解锁':'先看解析，再修复错题'}</h2><p>答对 ${right}/${unitOneQuiz.length} 题。</p></div><h2 class="review-title">逐题解析</h2><div class="answer-review">${reviews.map((r,i)=>`<article class="${r.ok?'correct-item':'wrong-item'}"><span>${r.ok?'✓ 回答正确':'× 回答错误'} · ${r.x.type}</span><h3>${i+1}. ${r.x.q}</h3><p>你的答案：<b>${r.x.opts[r.picked]}</b></p>${r.ok?'':`<p>正确答案：<b>${r.x.opts[r.x.a]}</b></p>`}<div>${r.x.why}</div></article>`).join('')}</div>`;e.currentTarget.hidden=true;result.scrollIntoView({behavior:'smooth'})}}
document.querySelector('#lessonClose').onclick=()=>document.querySelector('#lessonBackdrop').hidden=true;document.querySelector('#lessonBackdrop').onclick=e=>{if(e.target.id==='lessonBackdrop')e.currentTarget.hidden=true};document.querySelector('#lessonComplete').onclick=()=>{const checks=[...document.querySelectorAll('#lessonContent input')];if(!checks.every(c=>c.checked)){document.querySelector('#lessonWarning').textContent='请先完成并勾选上面的 3 个学习步骤。';return}const d=Number(document.querySelector('#lessonComplete').dataset.day);courseState.lessonDone[`${courseState.unit}-${d}`]=true;courseState.day=Math.max(courseState.day,d+1);document.querySelector('#lessonBackdrop').hidden=true;persistCourse();renderCourseInteractive()};
function openRealLesson(dayIndex){const unit=courseUnits[Math.max(0,(courseState.unit||1)-1)];if(dayIndex===7){document.querySelector('#lessonBackdrop').hidden=true;document.querySelector('[data-view-link="exam"]').click();renderExamByUnit();return}if(unit.n!==2){openLesson(dayIndex);return}const mat=unitTwoMaterial[dayIndex],lesson=dailyLessons[2][dayIndex-1];document.querySelector('#lessonLabel').textContent=`UNIT 2 · DAY ${dayIndex}`;document.querySelector('#lessonTitle').textContent=mat.title;document.querySelector('#lessonLead').textContent=mat.intro;document.querySelector('#lessonContent').innerHTML=`<div class="mastery-box"><small>本课掌握标准</small><b>${lesson[2]}</b></div>${mat.audio?`<button class="lesson-audio" id="lessonAudio">▶ 先听练习句</button>`:''}<div class="knowledge-sections">${mat.sections.map(s=>`<article><span>${s[0]}</span><p>${s[1]}</p></article>`).join('')}</div><div class="mini-practice"><span>即时检查</span><h3>${mat.practice.q}</h3>${mat.practice.opts.map((o,i)=>`<label><input type="radio" name="lessonPractice" value="${i}">${o}</label>`).join('')}<p id="practiceFeedback"></p></div>`;if(mat.audio)document.querySelector('#lessonAudio').onclick=()=>speakKorean(mat.audio,.82);document.querySelector('#lessonWarning').textContent='';document.querySelector('#lessonComplete').dataset.day=dayIndex;document.querySelector('#lessonComplete').dataset.answer=mat.practice.a;document.querySelector('#lessonComplete').textContent='提交练习并完成本课';document.querySelector('#lessonBackdrop').hidden=false}
function renderExamByUnit(){const unitNo=courseState.unit>=2?2:1,quiz=unitNo===2?unitTwoQuiz:unitOneQuiz,previous=courseState.passed?.[unitNo];document.querySelector('#examCenter').innerHTML=`<div class="exam-intro"><span>第 ${unitNo} 单元结业考 · 约 8 分钟</span><h2>${previous?`上次成绩 ${previous} 分`:`确认第 ${unitNo} 单元是否真正掌握`}</h2><p>交卷后立即逐题显示正确答案与讲解。达到 80 分才算通过。</p></div><form id="unitQuiz">${quiz.map((x,i)=>`<fieldset><legend><span>${x.type}</span>${i+1}. ${x.q}</legend>${x.opts.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}">${o}</label>`).join('')}</fieldset>`).join('')}<button class="submit-exam">提交并查看逐题解析</button></form><div id="examResult"></div>`;document.querySelector('#unitQuiz').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),missing=quiz.findIndex((_,i)=>form.get(`q${i}`)===null),result=document.querySelector('#examResult');if(missing>=0){result.innerHTML=`<div class="result-card retry"><h2>还有题目没有回答</h2><p>请完成第 ${missing+1} 题后再提交。</p></div>`;return}let right=0;const reviews=[];mistakeState=mistakeState.filter(m=>m.exam!==`unit-${unitNo}`);quiz.forEach((x,i)=>{const picked=Number(form.get(`q${i}`)),ok=picked===x.a;if(ok)right++;else mistakeState.push({id:`u${unitNo}-${i}`,exam:`unit-${unitNo}`,type:x.type,q:x.q,your:x.opts[picked],answer:x.opts[x.a],why:x.why,reviewed:false});reviews.push({x,picked,ok})});const score=Math.round(right/quiz.length*100);courseState.passed[unitNo]=score;if(score>=80&&unitNo===2){courseState.unit=3;courseState.day=1}persistCourse({rerenderExam:false});result.innerHTML=`<div class="result-card ${score>=80?'pass':'retry'}"><strong>${score}</strong><h2>${score>=80?'通过！下一单元已解锁':'先看解析，再修复错题'}</h2><p>答对 ${right}/${quiz.length} 题。</p></div><h2 class="review-title">逐题解析</h2><div class="answer-review">${reviews.map((r,i)=>`<article class="${r.ok?'correct-item':'wrong-item'}"><span>${r.ok?'✓ 回答正确':'× 回答错误'} · ${r.x.type}</span><h3>${i+1}. ${r.x.q}</h3><p>你的答案：<b>${r.x.opts[r.picked]}</b></p>${r.ok?'':`<p>正确答案：<b>${r.x.opts[r.x.a]}</b></p>`}<div>${r.x.why}</div></article>`).join('')}</div>`;e.currentTarget.hidden=true;result.scrollIntoView({behavior:'smooth'})}}
openLesson=openRealLesson;renderExam=renderExamByUnit;renderCourse();renderExam();renderMistakes();
document.querySelector('#lessonComplete').onclick=()=>{const day=Number(document.querySelector('#lessonComplete').dataset.day),answer=document.querySelector('#lessonComplete').dataset.answer;if(answer!==undefined){const picked=document.querySelector('input[name="lessonPractice"]:checked'),feedback=document.querySelector('#practiceFeedback');if(!picked){feedback.textContent='请先完成即时检查。';return}if(Number(picked.value)!==Number(answer)){feedback.textContent='还不对，请回看上面的知识讲解后再选一次。';return}feedback.textContent='✓ 回答正确，本课达标！'}courseState.lessonDone[`${courseState.unit}-${day}`]=true;courseState.day=Math.max(courseState.day,day+1);document.querySelector('#lessonBackdrop').hidden=true;persistCourse();renderCourseInteractive()};
