const loanWords=new Set(['컴퓨터','메뉴','도서관 카드']);
const nativeWords=new Set(['옆','뒤','가방','책','지우개','자','빌리다','물','내일','비빔밥','김밥','숟가락','젓가락']);
const etymologyExtra={
'컴퓨터':'英语外来语：computer → 컴퓨터。按韩语音节 컴-퓨-터 读，看到英文即可反推。','메뉴':'英语/法语外来语：menu → 메뉴。拼写和读音都非常接近英文。','도서관 카드':'混合词：도서관（图书馆，汉字词）+ card → 카드。',
'가방':'可能经日语进入韩语，现代韩语直接作为“包”使用；用“把 가방 背上”的动作记，不强套中文谐音。','책':'固有使用频率极高的“书”；把发音和合书时短促收住的声音绑定。','옆':'固有位置词；把一个人紧贴在你旁边的画面与短促收音绑定。','뒤':'固有位置词；转身指向背后，同时说 뒤。','지우개':'韩语构词：지우다（擦掉）+ -개（工具）= 用来擦掉的东西。','빌리다':'韩语动词“借入”；和 반납하다（归还）成对记。','물':'韩语固有词“水”；喝水动作与一个音节 물 直接绑定。','내일':'韩语固有词“明天”；和 오늘（今天）、어제（昨天）组成时间组。','비빔밥':'韩语构词：비비다（拌）+ 밥（饭）= 拌饭。','김밥':'韩语构词：김（紫菜）+ 밥（饭）= 紫菜饭卷。','숟가락':'韩语构词，指勺类餐具；与 젓가락（筷子）成对记。','젓가락':'韩语构词，指夹取食物的细长餐具；与 숟가락 成对记。'};
function memoryMethod(word){if(loanWords.has(word))return ['英语外来语',etymologyExtra[word]||chineseMemory[word]];if(nativeWords.has(word))return ['固有词 / 韩语构词',etymologyExtra[word]||chineseMemory[word]];return ['汉字同源词',chineseMemory[word]]}
function refineVocabMethods(){document.querySelectorAll('.vocab-card-clean').forEach(card=>{const word=card.querySelector('h3')?.textContent,[type,note]=memoryMethod(word),box=card.querySelector('.native-memory');if(box)box.innerHTML=`<em>${type}</em>${note}`})}
const methodStage=renderStoryStage;renderStoryStage=stage=>{methodStage(stage);if(stage===1)refineVocabMethods()};

function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view-link]').forEach(b=>b.classList.toggle('active',b.dataset.viewLink===id));document.querySelector('#sidebar')?.classList.remove('open');location.hash=id;window.scrollTo(0,0);if(id==='mistakes'&&typeof renderMistakes==='function')renderMistakes()}
function simplifyNavigation(){const nav=document.querySelector('.sidebar nav'),items=[['home','⌂','今日'],['course','课','课程'],['learn','复','复习'],['listen','耳','听说训练'],['favorites','♡','收藏']];nav.innerHTML=items.map(x=>`<button data-view-link="${x[0]}" class="${location.hash.slice(1)===x[0]?'active':''}"><i>${x[1]}</i><span>${x[2]}</span></button>`).join('');nav.querySelectorAll('[data-view-link]').forEach(b=>b.onclick=e=>{e.preventDefault();const id=b.dataset.viewLink;showView(id);if(id==='listen')injectSpeakingShortcut();if(id==='learn')injectReviewShortcut()})}
function injectSpeakingShortcut(){const page=document.querySelector('#listen .page-head');if(!page.querySelector('.mode-switch'))page.insertAdjacentHTML('beforeend','<div class="mode-switch"><button class="on">听力</button><button id="goSpeaking">口语跟读</button></div>');document.querySelector('#goSpeaking').onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='speak'));location.hash='speak'}}
function injectReviewShortcut(){const page=document.querySelector('#learn .page-head');if(!page||page.querySelector('.review-mode-switch'))return;page.insertAdjacentHTML('beforeend','<div class="mode-switch review-mode-switch"><button class="on">单词复习</button><button id="goMistakes">错题修复</button></div>');document.querySelector('#goMistakes').onclick=()=>showView('mistakes')}
function wireMergedRoutes(){document.querySelectorAll('[data-plan-go="mistakes"]').forEach(b=>b.onclick=()=>showView('mistakes'))}
function learningMinutes(){const history=Object.values(courseState.history||{}),recorded=history.reduce((n,x)=>n+(x.reviewed||0)*1.5+(x.listened||0)*4+(x.spoken||0)*3,0);return Math.round(recorded)}
function composeDashboard(){const grid=document.querySelector('.dashboard-grid'),today=grid.querySelector('.today-card'),progress=grid.querySelector('.progress-card'),growth=grid.querySelector('.growth-card'),ability=grid.querySelector('.ability-card-home'),weekly=grid.querySelector('.weekly-card');if(!today||!growth||!ability||!weekly)return;grid.querySelectorAll('.overview-growth,.overview-report').forEach(x=>x.remove());const growthCard=document.createElement('article');growthCard.className='overview-growth';growthCard.innerHTML=`<div class="overview-head"><div><span class="soft-label">GROWTH · 成长总览</span><h2>${rankInfo().name}</h2><p>${rankInfo().next?`距离 ${rankTiers[rankInfo().index+1][0]} 还差 ${rankInfo().remain} 成长值`:'已到达最高目标段位'}</p></div><div class="mini-emblem">${rankInfo().score}<small>成长值</small></div></div><div class="growth-combined"><div class="ability-slot">${ability.querySelector('.radar-wrap').outerHTML}</div><div class="stats-slot">${growth.querySelector('.achievement-grid').outerHTML}<p>五维能力与段位都来自实际学习表现，不需要手动填写。</p></div></div>`;const report=document.createElement('article');report.className='overview-report';const week=weeklySummary(),todayStateValue=todayState();report.innerHTML=`<div class="report-title"><div><span class="soft-label">REPORT · 学习报告</span><h2>今天与本周</h2></div><div class="time-badge"><b>${learningMinutes()}</b><span>累计学习分钟</span></div></div><div class="report-progress"><div><b>${todayStateValue.reviewed||0}</b><span>今日复习词</span></div><div><b>${todayStateValue.listened||0}</b><span>今日听力</span></div><div><b>${todayStateValue.spoken||0}</b><span>今日口语</span></div><div><b>${week.days}</b><span>本周学习天</span></div></div><div class="week-insight"><b>${week.weak.length?'本周重点复习':'继续积累诊断数据'}</b><p>${week.weak.length?week.weak.join('、')+' 容易忘，已提高返场频率。':'完成一轮复习后，这里会出现薄弱项和复习建议。'}</p></div>`;today.after(growthCard,report);progress?.remove();growth.remove();ability.remove();weekly.remove();today.classList.add('dashboard-hero')}
const cleanGrowth=renderGrowthHome;renderGrowthHome=()=>{cleanGrowth();composeDashboard()};
const cleanRender=render;render=()=>{cleanRender();composeDashboard();refineVocabMethods();wireMergedRoutes();if(document.querySelector('#learn.active'))injectReviewShortcut();if(document.querySelector('#listen.active'))injectSpeakingShortcut()};
simplifyNavigation();render();
