const Notification=window.Notification;
const englishLexicon={
'학교':['school','/skuːl/'], '대학교':['university','/ˌjuːnɪˈvɜːrsəti/'], '교실':['classroom','/ˈklæsruːm/'], '도서관':['library','/ˈlaɪbreri/'], '학생회관':['student center','/ˈstuːdnt ˌsentər/'], '교육관':['education building','/ˌedʒuˈkeɪʃn ˈbɪldɪŋ/'], '정문':['main gate','/ˌmeɪn ˈɡeɪt/'], '옆':['beside','/bɪˈsaɪd/'], '뒤':['behind','/bɪˈhaɪnd/'],
'책상':['desk','/desk/'], '의자':['chair','/tʃer/'], '칠판':['blackboard','/ˈblækbɔːrd/'], '창문':['window','/ˈwɪndoʊ/'], '문':['door','/dɔːr/'], '컴퓨터':['computer','/kəmˈpjuːtər/'], '시계':['clock','/klɑːk/'], '지도':['map','/mæp/'], '쓰레기통':['trash can','/ˈtræʃ kæn/'],
'가방':['bag','/bæɡ/'], '책':['book','/bʊk/'], '공책':['notebook','/ˈnoʊtbʊk/'], '연필':['pencil','/ˈpensl/'], '지우개':['eraser','/ɪˈreɪsər/'], '필통':['pencil case','/ˈpensl keɪs/'], '자':['ruler','/ˈruːlər/'], '사전':['dictionary','/ˈdɪkʃəneri/'], '교과서':['textbook','/ˈtekstbʊk/'],
'책장':['bookshelf','/ˈbʊkʃelf/'], '사서':['librarian','/laɪˈbreriən/'], '학생증':['student ID','/ˈstuːdnt aɪˈdiː/'], '도서관 카드':['library card','/ˈlaɪbreri kɑːrd/'], '초급':['beginner level','/bɪˈɡɪnər ˈlevl/'], '중급':['intermediate level','/ˌɪntərˈmiːdiət ˈlevl/'], '빌리다':['borrow','/ˈbɑːroʊ/'], '반납하다':['return','/rɪˈtɜːrn/'], '읽다':['read','/riːd/'],
'학생 식당':['student cafeteria','/ˈstuːdnt ˌkæfəˈtɪriə/'], '메뉴':['menu','/ˈmenjuː/'], '비빔밥':['bibimbap','/ˈbiːbɪmbæp/'], '김밥':['gimbap','/ˈɡɪmbæp/'], '물':['water','/ˈwɔːtər/'], '반찬':['side dish','/ˈsaɪd dɪʃ/'], '숟가락':['spoon','/spuːn/'], '젓가락':['chopsticks','/ˈtʃɑːpstɪks/'], '쟁반':['tray','/treɪ/'],
'수업':['class','/klæs/'], '숙제':['homework','/ˈhoʊmwɜːrk/'], '시험':['exam','/ɪɡˈzæm/'], '공부하다':['study','/ˈstʌdi/'], '복습하다':['review','/rɪˈvjuː/'], '질문하다':['ask','/æsk/'], '오전':['morning','/ˈmɔːrnɪŋ/'], '오후':['afternoon','/ˌæftərˈnuːn/'], '내일':['tomorrow','/təˈmɑːroʊ/']};
const rankTiers=[['青铜新芽','막 시작','0–99'],['白银海风','첫걸음','100–249'],['黄金晴空','기초 회화','250–449'],['铂金浪花','생활 한국어','450–699'],['钻石星光','TOPIK 1','700–999'],['大师极光','TOPIK 2','1000–1399'],['宗师银河','TOPIK 3','1400–1899'],['王者朝阳','TOPIK 4','1900+']];
function speakEnglish(text){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;u.voice=speechSynthesis.getVoices().find(v=>/^en(-|_)/i.test(v.lang)&&/samantha|ava|google us english/i.test(v.name))||speechSynthesis.getVoices().find(v=>/^en/i.test(v.lang))||null;speechSynthesis.cancel();speechSynthesis.speak(u)}
function growthScore(){const passed=Object.values(courseState.lessonScores||{}).filter(v=>v>=80).length,mem=Object.values(courseState.memory||{}),stable=mem.filter(x=>x.interval>=3).length,attempts=mem.reduce((n,x)=>n+(x.seen||0),0),activity=Object.values(courseState.history||{}).reduce((n,x)=>n+(x.reviewed||0)+(x.listened||0)*2+(x.spoken||0)*2,0);return passed*90+stable*18+Math.min(attempts,200)*2+Math.min(activity,300)}
function rankInfo(){const score=growthScore(),limits=[0,100,250,450,700,1000,1400,1900],index=Math.max(0,limits.findLastIndex(x=>score>=x)),next=limits[index+1];return {score,index,name:rankTiers[index][0],next,remain:next?next-score:0,progress:next?Math.round((score-limits[index])/(next-limits[index])*100):100}}
function updateHistory(){todayState();courseState.history=courseState.history||{};courseState.startedAt=courseState.startedAt||Date.now();courseState.history[courseState.today.date]={reviewed:courseState.today.reviewed||0,listened:courseState.today.listened||0,spoken:courseState.today.spoken||0};localStorage.setItem('malbit-course',JSON.stringify(courseState))}
function abilities(){const passed=Object.values(courseState.lessonScores||{}).filter(v=>v>=80).length,mem=Object.values(courseState.memory||{}),total=Math.max(mem.length,9),stable=mem.filter(x=>x.interval>=1).length,history=Object.values(courseState.history||{}),listened=history.reduce((n,x)=>n+(x.listened||0),0),spoken=history.reduce((n,x)=>n+(x.spoken||0),0),best=scores._bestSpeech||0;return {词汇:Math.min(100,Math.round(stable/total*100)),语法:Math.min(100,15+passed*14),听力:Math.min(100,10+listened*8+passed*5),口语:Math.min(100,Math.max(best,10+spoken*8)),发音:Math.min(100,Math.max(Math.round(best*.85),10+spoken*6))}}
function pentagonPoints(values,radius=46,cx=50,cy=50){return Object.values(values).map((v,i)=>{const a=(-90+i*72)*Math.PI/180,r=radius*v/100;return `${cx+Math.cos(a)*r},${cy+Math.sin(a)*r}`}).join(' ')}
function weeklySummary(){updateHistory();const entries=Object.entries(courseState.history).sort().slice(-7),totals=entries.reduce((a,[,v])=>({reviewed:a.reviewed+(v.reviewed||0),listened:a.listened+(v.listened||0),spoken:a.spoken+(v.spoken||0)}),{reviewed:0,listened:0,spoken:0}),weak=Object.entries(courseState.memory||{}).sort((a,b)=>(b[1].lapses||0)-(a[1].lapses||0)).filter(x=>x[1].lapses).slice(0,3).map(x=>x[0]),scoresList=Object.values(courseState.lessonScores||{}),avg=scoresList.length?Math.round(scoresList.reduce((a,b)=>a+b,0)/scoresList.length):0;return {days:entries.filter(([,v])=>(v.reviewed||0)+(v.listened||0)+(v.spoken||0)>0).length,...totals,weak,avg}}
function renderGrowthHome(){updateHistory();const rank=rankInfo(),ab=abilities(),week=weeklySummary(),days=Object.values(courseState.history).filter(v=>(v.reviewed||0)+(v.listened||0)+(v.spoken||0)>0).length,learned=Object.keys(courseState.memory||{}).length,passed=Object.values(courseState.lessonScores||{}).filter(v=>v>=80).length,container=document.querySelector('.dashboard-grid');container.querySelectorAll('.growth-card,.ability-card-home,.weekly-card').forEach(x=>x.remove());container.insertAdjacentHTML('beforeend',`<article class="growth-card"><span class="soft-label">RANK · 我的段位</span><div class="rank-emblem"><small>${rankTiers[rank.index][1]}</small><strong>${rank.name}</strong><span>${rank.score} 成长值</span></div><div class="rank-progress"><i style="width:${rank.progress}%"></i></div><p>${rank.next?`距离 ${rankTiers[rank.index+1][0]} 还差 <b>${rank.remain}</b> 成长值`:'已到达当前最高段位：TOPIK 4 目标段'}</p><div class="achievement-grid"><div><b>${learned}</b><span>学过词汇</span></div><div><b>${passed}</b><span>通过课程</span></div><div><b>${days}</b><span>学习天数</span></div><div><b>${Object.values(courseState.memory||{}).filter(x=>x.interval>=3).length}</b><span>稳定记住</span></div></div></article><article class="ability-card-home"><span class="soft-label">ABILITY · 韩语五维能力</span><div class="radar-wrap"><div class="radar-label top">发音 ${ab.发音}</div><div class="radar-label right-top">口语 ${ab.口语}</div><div class="radar-label right-bottom">听力 ${ab.听力}</div><div class="radar-label left-bottom">词汇 ${ab.词汇}</div><div class="radar-label left-top">语法 ${ab.语法}</div><svg viewBox="0 0 100 100" aria-label="韩语五维能力图"><polygon class="radar-grid" points="50,4 93.7,35.8 77,87.2 23,87.2 6.3,35.8"/><polygon class="radar-mid" points="50,27 71.8,42.9 63.5,68.6 36.5,68.6 28.2,42.9"/><polygon class="radar-value" points="${pentagonPoints(ab)}"/></svg></div><p>能力值来自课程测试、间隔复习、听力次数和口语表现，不由手动勾选决定。</p></article><article class="weekly-card"><span class="soft-label">WEEKLY · 本周学习周报</span><h3>${week.days?`本周坚持了 ${week.days} 天`:'本周从今天开始积累'}</h3><div class="weekly-numbers"><div><b>${week.reviewed}</b><span>词汇提取</span></div><div><b>${week.listened}</b><span>听力练习</span></div><div><b>${week.spoken}</b><span>口语练习</span></div><div><b>${week.avg||'—'}</b><span>课程均分</span></div></div><p>${week.weak.length?`当前薄弱词：${week.weak.join('、')}。下周会提高它们的出现频率。`:'目前还没有明显薄弱词，继续完成首次复习后会生成诊断。'}</p><button id="weeklyNotify">${Notification?.permission==='granted'?'✓ 周报提醒已开启':'开启每周周报提醒'}</button><small>每周一自动生成新周报；允许通知后，在你打开网站时会提醒查看。</small></article>`);document.querySelector('#weeklyNotify').onclick=async()=>{if(!('Notification'in window))return alert('当前浏览器不支持网页通知');const permission=await Notification.requestPermission();document.querySelector('#weeklyNotify').textContent=permission==='granted'?'✓ 周报提醒已开启':'未获得通知权限';if(permission==='granted')new Notification('语光周报已开启',{body:'每周一回来看看本周学习总结和薄弱项。'})}}
function enhanceCurrentWord(){const d=reviewQueue()[courseWordIndex%reviewQueue().length],en=englishLexicon[d.word]||['—','—'],card=document.querySelector('#card');let panel=card.querySelector('.cross-language');if(!panel){panel=document.createElement('span');panel.className='cross-language';card.querySelector('#hint').before(panel)}panel.innerHTML=`<b>中文</b> ${d.meaning}<i>↔</i><b>English</b> ${en[0]} <small>${en[1]}</small>`;panel.onclick=e=>{e.stopPropagation();speakEnglish(en[0])};const tip=document.querySelector('.tip span');tip.textContent=`跨语言联想：${d.word} = ${d.meaning} = ${en[0]}。英文只是增加一条检索线索，最终仍要直接从场景想起韩语。`}
function addEnglishToLesson(){document.querySelectorAll('.vocab-deck [data-word]').forEach(b=>{if(b.querySelector('.english-pair'))return;const korean=b.querySelector('b')?.textContent,en=englishLexicon[korean];if(en)b.insertAdjacentHTML('beforeend',`<span class="english-pair">EN · ${en[0]} <small>${en[1]}</small><button data-en-say="${en[0]}">🔊</button></span>`)});document.querySelectorAll('[data-en-say]').forEach(b=>b.onclick=e=>{e.stopPropagation();speakEnglish(b.dataset.enSay)})}
const growthStageRender=renderStoryStage;renderStoryStage=stage=>{growthStageRender(stage);if(stage===1)addEnglishToLesson()};
const growthWordRender=renderCourseWord;renderCourseWord=()=>{growthWordRender();enhanceCurrentWord()};
const growthSaveMemory=saveMemory;saveMemory=()=>{updateHistory();growthSaveMemory()};
const growthRender=render;render=()=>{growthRender();enhanceCurrentWord();renderGrowthHome()};
function showVoiceHelp(){const voices=koreanVoices();if(voices.length<=1){const bar=document.querySelector('.voice-bar');bar?.insertAdjacentHTML('beforeend','<span class="voice-help">当前设备只有基础韩语音色。iPhone 可到“设置 → 辅助功能 → 朗读内容 → 声音 → 韩语”，下载增强音色后重新打开网页。</span>')}}
const growthOpenStory=openStoryLesson;openStoryLesson=(day,stage=0)=>{growthOpenStory(day,stage);if(stage===0)showVoiceHelp()};
const voiceChoiceOpenStory=openStoryLesson;openStoryLesson=(day,stage=0)=>{voiceChoiceOpenStory(day,stage);if(stage===0){const bar=document.querySelector('.voice-bar'),voices=koreanVoices();if(voices.length&&!document.querySelector('#qualityVoiceSelect')){bar.insertAdjacentHTML('beforeend',`<label>韩语音色 <select id="qualityVoiceSelect">${voices.map(v=>`<option value="${v.name}">${v.name}${v.localService?' · 本机':''}</option>`).join('')}</select></label>`);const select=document.querySelector('#qualityVoiceSelect');select.value=localStorage.getItem('malbit-korean-voice')||voices[0].name;select.onchange=()=>{localStorage.setItem('malbit-korean-voice',select.value);speakKorean('안녕하세요. 오늘도 같이 공부해요.',.86)}}}};
const baseGrowthHome=renderGrowthHome;renderGrowthHome=()=>{baseGrowthHome();const rank=rankInfo();document.querySelector('#status').textContent=`${rank.name} · ${rank.score} 成长值`;const now=new Date(),weekKey=`${now.getFullYear()}-${Math.ceil((((now-new Date(now.getFullYear(),0,1))/864e5)+new Date(now.getFullYear(),0,1).getDay()+1)/7)}`;if(now.getDay()===1&&Notification?.permission==='granted'&&localStorage.getItem('malbit-week-notified')!==weekKey){localStorage.setItem('malbit-week-notified',weekKey);new Notification('你的语光学习周报已生成',{body:'看看本周学了什么、薄弱在哪里，以及下周复习重点。'})}};
render();
