const chineseMemory={
'학교':'汉字词“学校”，학=学、교=校；和中文“学校”同源。','대학교':'汉字词“大学校”，대=大、학=学、교=校，拆开就不会忘。','교실':'汉字词“教室”，读音 교실 也很像中文“教师/教室”，直接用中文搭桥。','도서관':'汉字词“图书馆”：도서=图书、관=馆。','학생회관':'학생=学生，회관=会馆；就是“学生会馆”。','교육관':'교육=教育，관=馆；教育馆/教学楼。','정문':'汉字词“正门”，정=正、문=门。','옆':'想象朋友贴在你“旁边”，短促读 옆，嘴巴也立刻收住。','뒤':'读音像“堆”，想象书包堆在椅子后面。',
'책상':'책=书，상=床/桌的“床”音；放书的台面就是书桌。','의자':'汉字词“椅子”，韩语 의자 与中文“椅子”同源。','칠판':'汉字词“漆板”，칠=漆、판=板，也就是黑板。','창문':'창=窗、문=门，两个中文概念拼成“窗户”。','문':'和汉字“门”同源；看到门就说 문。','컴퓨터':'英语 computer 的韩语外来词，按韩语音节 컴-퓨-터 记。','시계':'汉字词“时计”，计时的东西就是钟表。','지도':'汉字词“地图”，词序和中文完全相同。','쓰레기통':'쓰레기=垃圾，통=桶；就是“垃圾桶”。',
'가방':'想象把包“嘎嘣”一声扣上：가방=包。','책':'把 책 和 book 的合页“啪”地合上，ㄱ 收音立刻收住。','공책':'공=空，책=书；还没写内容的“空书”就是笔记本。','연필':'汉字词“铅笔”，연=铅、필=笔，与中文完全同源。','지우개':'지우다=擦掉，-개=工具；“用来擦掉的东西”就是橡皮。','필통':'필=笔、통=筒；笔筒/笔袋。','자':'把尺子摆成一条直线，短短一个音 자。','사전':'汉字词“辞典”，사=辞、전=典，也就是词典。','교과서':'汉字词“教科书”，与中文课本概念完全一致。',
'책장':'책=书、장=柜/橱；放书的柜架。','사서':'汉字词“司书”，负责管理书的人就是图书管理员。','학생증':'학생=学生、증=证；学生证。','도서관 카드':'도서관=图书馆，카드来自 card；图书馆卡。','초급':'汉字词“初级”，초=初、급=级。','중급':'汉字词“中级”，중=中、급=级。','빌리다':'想象向朋友“借来”一本书：빌리다=借入。','반납하다':'汉字词“返纳”，把借来的东西返还缴回。','읽다':'把书“一刻一刻”读完；实际读音 [익따]。',
'학생 식당':'학생=学生、식당=食堂；与中文“学生食堂”几乎一一对应。','메뉴':'英语 menu 的韩语外来词。','비빔밥':'비비다=拌，밥=饭；“拌起来的饭”就是拌饭。','김밥':'김=紫菜、밥=饭；紫菜包着饭。','물':'想象喝水时“咕噜”一口，물=水。','반찬':'汉字词“饭馔”，配饭吃的小菜。','숟가락':'숟=勺，가락=细长用具；勺子。','젓가락':'젓=夹取，가락=细长用具；筷子。','쟁반':'汉字词“铮盘/盘”，想象食堂端着托盘。',
'수업':'汉字词“授业”，老师授课、学生上课。','숙제':'汉字词“宿题”，带回去完成的题就是作业。','시험':'汉字词“试验”，在学校语境就是考试。','공부하다':'공부 是汉字词“工夫”，花工夫做的事就是学习。','복습하다':'汉字词“复习”，복=复、습=习，与中文完全同源。','질문하다':'汉字词“质问”，现代韩语常表示提问。','오전':'汉字词“午前”，即上午。','오후':'汉字词“午后”，即下午。','내일':'把“明天的我”想成 내일의 나，整组记住 내일=明天。'};

function rebuildVocabCards(){document.querySelectorAll('.vocab-deck > button[data-word]').forEach(old=>{const i=Number(old.dataset.word),l=storyLessons[activeStoryLesson-1],d=wordDetail(l.words[i][0],l.words[i][1],activeStoryLesson),en=englishLexicon[d.word]||['—','—'],article=document.createElement('article');article.className='vocab-card-clean';article.innerHTML=`<small>${String(i+1).padStart(2,'0')}</small><h3>${d.word}</h3><span>${d.meaning}</span><button class="ko-audio" aria-label="播放${d.word}的韩语发音">🔊 韩语</button><b>[${d.pron}]</b><p>${d.rule}</p><div class="native-memory"><em>中文母语联想</em>${chineseMemory[d.word]||d.memory}</div><div class="english-clean"><span>EN · ${en[0]} <small>${en[1]}</small></span><button aria-label="播放${en[0]}的英语发音">🔊 英语</button></div>`;article.querySelector('.ko-audio').onclick=()=>speakKorean(d.word,.8);article.querySelector('.english-clean button').onclick=()=>speakEnglish(en[0]);old.replaceWith(article)})}
const summerStage=renderStoryStage;renderStoryStage=stage=>{summerStage(stage);if(stage===1)rebuildVocabCards()};
function refreshMnemonicCard(){const q=reviewQueue(),d=q[courseWordIndex%q.length],tip=document.querySelector('.tip span');if(tip)tip.textContent=`中文母语联想：${chineseMemory[d.word]||d.memory}`}
const summerWord=renderCourseWord;renderCourseWord=()=>{summerWord();refreshMnemonicCard()};
const summerGrowth=renderGrowthHome;renderGrowthHome=()=>{summerGrowth();document.querySelector('.memory-card')?.remove();document.querySelector('.today-card')?.classList.add('mosaic-today')};
const summerRender=render;render=()=>{summerRender();refreshMnemonicCard();document.querySelector('.memory-card')?.remove()};
render();
